// Boundary rules for feature assembly and optional dependency ownership.

export const optionalDependencyFeatureOwnerRules = [
  {
    crateName: 'core',
    reason:
      'bitfun-core product/runtime optional dependencies must stay owned by explicit feature gates',
    dependencies: [
      { depName: 'aes-gcm', ownerFeatures: ['service-integrations'] },
      { depName: 'axum', ownerFeatures: ['service-integrations'] },
      { depName: 'bitfun-ai-adapters', ownerFeatures: ['ai-adapter-runtime'] },
      { depName: 'bitfun-product-capabilities', ownerFeatures: ['product-capabilities'] },
      { depName: 'bitfun-product-domains', ownerFeatures: ['product-domains'] },
      { depName: 'bitfun-tool-packs', ownerFeatures: ['tool-packs'] },
      { depName: 'chrono-tz', ownerFeatures: ['product-full'] },
      { depName: 'cron', ownerFeatures: ['product-full'] },
      { depName: 'dashmap', ownerFeatures: ['product-full'] },
      { depName: 'eventsource-stream', ownerFeatures: ['product-full'] },
      { depName: 'filetime', ownerFeatures: ['product-full'] },
      { depName: 'flate2', ownerFeatures: ['product-full'] },
      { depName: 'fs2', ownerFeatures: ['product-full'] },
      { depName: 'git2', ownerFeatures: ['service-integrations'] },
      { depName: 'glob', ownerFeatures: ['product-full'] },
      { depName: 'globset', ownerFeatures: ['product-full'] },
      { depName: 'image', ownerFeatures: ['service-integrations', 'tool-packs'] },
      { depName: 'include_dir', ownerFeatures: ['product-full'] },
      { depName: 'indexmap', ownerFeatures: ['product-full'] },
      { depName: 'md5', ownerFeatures: ['product-full', 'service-integrations'] },
      { depName: 'rand', ownerFeatures: ['service-integrations'] },
      { depName: 'reqwest', ownerFeatures: ['ai-adapter-runtime', 'service-integrations'] },
      { depName: 'rmcp', ownerFeatures: ['service-integrations'] },
      { depName: 'russh', ownerFeatures: ['ssh-remote'] },
      { depName: 'similar', ownerFeatures: ['product-full'] },
      { depName: 'sse-stream', ownerFeatures: ['service-integrations'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['service-integrations'] },
      { depName: 'tower-http', ownerFeatures: ['service-integrations'] },
      { depName: 'tool-runtime', ownerFeatures: ['product-full'] },
    ],
  },
  {
    crateName: 'services-integrations',
    reason:
      'services-integrations optional runtime dependencies must stay owned by explicit integration features',
    dependencies: [
      { depName: 'aes', ownerFeatures: ['remote-connect'] },
      { depName: 'aes-gcm', ownerFeatures: ['mcp', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'anyhow', ownerFeatures: ['browser-control', 'debug-log', 'mcp', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete'] },
      {
        depName: 'async-trait',
        ownerFeatures: ['mcp', 'remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'script-tool-runtime', 'workspace-search'],
      },
      {
        depName: 'base64',
        ownerFeatures: ['mcp', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete'],
      },
      { depName: 'bitfun-agent-runtime', ownerFeatures: ['deep-research'] },
      { depName: 'bitfun-product-domains', ownerFeatures: ['canvas-runtime', 'function-agents', 'miniapp-runtime', 'plugin-source'] },
      { depName: 'bitfun-runtime-ports', ownerFeatures: ['remote-connect', 'remote-ssh', 'remote-ssh-concrete', 'script-tool-runtime'] },
      {
        depName: 'bitfun-services-core',
        ownerFeatures: ['browser-control', 'git', 'mcp', 'miniapp-runtime', 'remote-connect', 'review-platform', 'workspace-search'],
      },
      { depName: 'chrono', ownerFeatures: ['debug-log', 'git', 'remote-connect', 'remote-ssh-concrete', 'review-platform'] },
      { depName: 'dirs', ownerFeatures: ['browser-control', 'miniapp-runtime', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'dunce', ownerFeatures: ['plugin-source', 'remote-ssh', 'workspace-search'] },
      { depName: 'fs2', ownerFeatures: ['plugin-source'] },
      { depName: 'futures', ownerFeatures: ['mcp', 'remote-connect', 'review-platform'] },
      { depName: 'git2', ownerFeatures: ['git'] },
      { depName: 'hex', ownerFeatures: ['plugin-source', 'remote-connect'] },
      { depName: 'hostname', ownerFeatures: ['remote-connect'] },
      { depName: 'image', ownerFeatures: ['remote-connect'] },
      { depName: 'local-ip-address', ownerFeatures: ['remote-connect'] },
      { depName: 'libc', ownerFeatures: ['plugin-source'] },
      { depName: 'mac_address', ownerFeatures: ['remote-connect'] },
      { depName: 'md5', ownerFeatures: ['remote-connect'] },
      { depName: 'notify', ownerFeatures: ['file-watch'] },
      { depName: 'oxc', ownerFeatures: ['canvas-runtime'] },
      { depName: 'qrcode', ownerFeatures: ['remote-connect'] },
      { depName: 'rand', ownerFeatures: ['mcp', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'reqwest', ownerFeatures: ['announcement', 'browser-control', 'debug-log', 'mcp', 'miniapp-runtime', 'remote-connect', 'review-platform', 'web-tools'] },
      { depName: 'rmcp', ownerFeatures: ['mcp'] },
      { depName: 'russh', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-keys', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'russh-sftp', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'rustls', ownerFeatures: ['remote-connect'] },
      { depName: 'rustls-native-certs', ownerFeatures: ['remote-connect'] },
      { depName: 'schannel', ownerFeatures: ['remote-connect'] },
      { depName: 'sha2', ownerFeatures: ['canvas-runtime', 'plugin-source', 'remote-connect', 'remote-ssh', 'review-platform'] },
      { depName: 'shellexpand', ownerFeatures: ['remote-ssh-concrete'] },
      { depName: 'sse-stream', ownerFeatures: ['mcp'] },
      { depName: 'ssh_config', ownerFeatures: ['remote-ssh-concrete', 'ssh_config'] },
      { depName: 'terminal-core', ownerFeatures: ['remote-ssh', 'remote-ssh-concrete'] },
      { depName: 'thiserror', ownerFeatures: ['browser-control', 'git', 'plugin-source', 'remote-ssh', 'remote-ssh-concrete', 'review-platform', 'web-tools', 'workspace-search'] },
      { depName: 'tokio-tungstenite', ownerFeatures: ['remote-connect'] },
      { depName: 'tokio-util', ownerFeatures: ['remote-ssh'] },
      { depName: 'urlencoding', ownerFeatures: ['canvas-runtime', 'remote-connect', 'review-platform'] },
      { depName: 'uuid', ownerFeatures: ['canvas-runtime', 'debug-log', 'miniapp-runtime', 'plugin-source', 'remote-connect', 'remote-ssh-concrete'] },
      { depName: 'which', ownerFeatures: ['miniapp-runtime', 'remote-connect', 'script-tool-runtime', 'workspace-search'] },
      { depName: 'windows', ownerFeatures: ['plugin-source', 'review-platform'] },
      { depName: 'x25519-dalek', ownerFeatures: ['remote-connect'] },
    ],
  },
  {
    crateName: 'product-domains',
    reason:
      'product-domains optional runtime dependencies must stay owned by explicit product-domain features',
    dependencies: [
      { depName: 'dirs', ownerFeatures: ['miniapp'] },
      { depName: 'log', ownerFeatures: ['function-agents'] },
      { depName: 'hex', ownerFeatures: ['external-sources', 'plugin-source'] },
      { depName: 'sha2', ownerFeatures: ['external-sources', 'miniapp', 'plugin-source'] },
      { depName: 'which', ownerFeatures: ['miniapp'] },
    ],
  },
];

export const productCoreFeatureAssemblyRules = [
  {
    manifestPath: 'src/apps/desktop/Cargo.toml',
    dependencyName: 'bitfun-core',
    requiredFeatures: ['product-full'],
    reason: 'desktop must explicitly assemble the full bitfun-core product runtime',
  },
  {
    manifestPath: 'src/apps/cli/Cargo.toml',
    dependencyName: 'bitfun-core',
    requiredFeatures: ['product-full'],
    reason: 'CLI must explicitly assemble the full bitfun-core product runtime',
  },
  {
    manifestPath: 'src/apps/server/Cargo.toml',
    dependencyName: 'bitfun-core',
    requiredFeatures: ['product-full'],
    reason: 'Server must explicitly assemble the full bitfun-core product runtime',
  },
  {
    manifestPath: 'src/crates/interfaces/acp/Cargo.toml',
    dependencyName: 'bitfun-core',
    requiredFeatures: ['product-full'],
    reason: 'ACP must explicitly assemble the full bitfun-core product runtime',
  },
];

export const productCoreFeatureAssemblyScanRoots = [
  'src/apps',
  'src/crates/interfaces/acp',
];

export const coreProductFullFeatureAssemblyRule = {
  manifestPath: 'src/crates/assembly/core/Cargo.toml',
  featureName: 'product-full',
  requiredFeatureRefs: [
    'ssh-remote',
    'product-capabilities',
    'product-domains',
    'service-integrations',
    'tool-packs',
  ],
  reason: 'bitfun-core product-full must explicitly assemble current owner feature groups',
};

export const ownerCrateFeatureAssemblyRules = [
  {
    manifestPath: 'src/crates/execution/tool-provider-groups/Cargo.toml',
    reason: 'tool-packs must keep product feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'basic',
      'git',
      'mcp',
      'browser-web',
      'computer-use',
      'image-analysis',
      'miniapp',
      'canvas',
      'agent-control',
    ],
  },
  {
    manifestPath: 'src/crates/services/services-integrations/Cargo.toml',
    reason: 'services-integrations must keep integration feature groups explicit and default-light',
    requiredProductFullFeatures: [
      'announcement',
      'browser-control',
      'canvas-runtime',
      'debug-log',
      'deep-research',
      'file-watch',
      'function-agents',
      'git',
      'miniapp-runtime',
      'mcp',
      'plugin-source',
      'remote-connect',
      'remote-ssh',
      'remote-ssh-concrete',
      'review-platform',
      'script-tool-runtime',
      'web-tools',
      'workspace-search',
    ],
  },
  {
    manifestPath: 'src/crates/contracts/product-domains/Cargo.toml',
    reason: 'product-domains must keep product domain feature groups explicit and default-light',
    requiredProductFullFeatures: ['plugin-source', 'miniapp', 'function-agents', 'external-sources'],
  },
];
