import { WIDGET_IFRAME_FALLBACK_COLOR } from '@/shared/theme/themeBoundaryFallbacks';

export type WidgetThemePayload = {
  id: string;
  type: string;
  vars: Record<string, string>;
};

const FALLBACK_VAR = {
  textPrimary: '--color-text-primary',
  textSecondary: '--color-text-secondary',
  textMuted: '--color-text-muted',
  accent500: '--color-accent-500',
  accent600: '--color-accent-600',
  bgSecondary: '--color-bg-secondary',
  success: '--color-success',
  warning: '--color-warning',
  error: '--color-error',
  staticWhite: '--color-static-white',
  borderSubtle: '--border-subtle',
  borderBase: '--border-base',
  borderMedium: '--border-medium',
  elementBgSubtle: '--element-bg-subtle',
  elementBgBase: '--element-bg-base',
  elementBgMedium: '--element-bg-medium',
  elementBgSoft: '--element-bg-soft',
  shadowXs: '--shadow-xs',
  shadowSm: '--shadow-sm',
} as const;

type WidgetThemeFallbackVarName = typeof FALLBACK_VAR[keyof typeof FALLBACK_VAR];

// Keep this fallback map small and self-contained. It is the last-resort iframe
// contract for static widget rendering before the host theme payload arrives.
export const WIDGET_THEME_FALLBACK_VARS = {
  [FALLBACK_VAR.textPrimary]: WIDGET_IFRAME_FALLBACK_COLOR.textPrimary,
  [FALLBACK_VAR.textSecondary]: WIDGET_IFRAME_FALLBACK_COLOR.textSecondary,
  [FALLBACK_VAR.textMuted]: WIDGET_IFRAME_FALLBACK_COLOR.textMuted,
  [FALLBACK_VAR.accent500]: WIDGET_IFRAME_FALLBACK_COLOR.accent500,
  [FALLBACK_VAR.accent600]: WIDGET_IFRAME_FALLBACK_COLOR.accent600,
  [FALLBACK_VAR.bgSecondary]: WIDGET_IFRAME_FALLBACK_COLOR.bgSecondary,
  [FALLBACK_VAR.success]: WIDGET_IFRAME_FALLBACK_COLOR.success,
  [FALLBACK_VAR.warning]: WIDGET_IFRAME_FALLBACK_COLOR.warning,
  [FALLBACK_VAR.error]: WIDGET_IFRAME_FALLBACK_COLOR.error,
  [FALLBACK_VAR.staticWhite]: WIDGET_IFRAME_FALLBACK_COLOR.staticWhite,
  [FALLBACK_VAR.borderSubtle]: WIDGET_IFRAME_FALLBACK_COLOR.borderSubtle,
  [FALLBACK_VAR.borderBase]: WIDGET_IFRAME_FALLBACK_COLOR.borderBase,
  [FALLBACK_VAR.borderMedium]: WIDGET_IFRAME_FALLBACK_COLOR.borderMedium,
  [FALLBACK_VAR.elementBgSubtle]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgSubtle,
  [FALLBACK_VAR.elementBgBase]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgBase,
  [FALLBACK_VAR.elementBgMedium]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgMedium,
  [FALLBACK_VAR.elementBgSoft]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgBase,
  [FALLBACK_VAR.shadowXs]: `0 1px 2px ${WIDGET_IFRAME_FALLBACK_COLOR.shadowBase}`,
  [FALLBACK_VAR.shadowSm]: `0 2px 4px ${WIDGET_IFRAME_FALLBACK_COLOR.shadowBase}`,
} as const satisfies Record<WidgetThemeFallbackVarName, string>;

export function createWidgetThemeFallbackCss(): string {
  return Object.entries(WIDGET_THEME_FALLBACK_VARS)
    .map(([name, value]) => `      ${name}: ${value};`)
    .join('\n');
}

// Host -> generated-widget iframe theme contract. Keep groups explicit so
// isolated widgets receive stable tokens without scraping every root variable.
const WIDGET_THEME_VAR_GROUPS = {
  staticAndOverlay: [
  '--color-bg-primary',
  FALLBACK_VAR.staticWhite,
  '--color-static-black',
  '--color-overlay-white-02',
  '--color-overlay-white-03',
  '--color-overlay-white-04',
  '--color-overlay-white-05',
  '--color-overlay-white-06',
  '--color-overlay-white-08',
  '--color-overlay-white-10',
  '--color-overlay-white-12',
  '--color-overlay-white-15',
  '--color-overlay-white-20',
  '--color-overlay-white-60',
  '--color-overlay-black-06',
  '--color-overlay-black-08',
  '--color-overlay-black-10',
  '--color-overlay-black-12',
  '--color-overlay-black-15',
  '--color-overlay-black-20',
  '--color-overlay-black-25',
  '--color-overlay-black-30',
  '--color-overlay-black-40',
  '--color-overlay-black-50',
  '--color-overlay-black-80',
  ],
  backgroundSurface: [
  FALLBACK_VAR.bgSecondary,
  '--color-bg-tertiary',
  '--color-bg-quaternary',
  '--color-bg-elevated',
  '--color-bg-workbench',
  '--color-bg-scene',
  '--color-bg-flowchat',
  '--color-bg-surface',
  '--color-bg-base',
  '--color-bg-subtle',
  '--color-bg-hover',
  '--color-bg-elevated-hover',
  '--color-hover',
  '--color-background-secondary',
  '--color-background-tertiary',
  '--background-primary',
  '--background-secondary',
  '--background-tertiary',
  '--bg-primary',
  '--bg-secondary',
  '--bg-tertiary',
  '--bg-elevated',
  '--bg-hover',
  '--secondary-bg',
  '--color-surface-elevated',
  '--color-surface-hover',
  '--color-bg-tooltip',
  ],
  text: [
  FALLBACK_VAR.textPrimary,
  FALLBACK_VAR.textSecondary,
  '--color-text-tertiary',
  '--text-primary',
  '--text-secondary',
  '--text-tertiary',
  '--text-muted',
  '--text-disabled',
  FALLBACK_VAR.textMuted,
  '--color-text-disabled',
  ],
  accent: [
  '--color-accent-50',
  '--color-accent-100',
  '--color-accent-200',
  '--color-accent-300',
  '--color-accent-400',
  FALLBACK_VAR.accent500,
  FALLBACK_VAR.accent600,
  '--color-accent-700',
  '--color-accent-800',
  '--color-accent',
  '--color-accent-primary',
  '--color-accent-alpha',
  '--color-primary',
  '--color-primary-rgb',
  '--color-primary-400',
  '--color-primary-hover',
  '--color-primary-500',
  '--color-primary-alpha',
  '--color-primary-bg',
  '--color-primary-bg-subtle',
  '--accent-primary',
  '--accent-primary-hover',
  ],
  semantic: [
  FALLBACK_VAR.success,
  '--color-success-bg',
  '--color-success-border',
  '--color-success-100',
  '--color-success-500',
  FALLBACK_VAR.warning,
  '--color-warning-bg',
  '--color-warning-border',
  '--color-warning-100',
  '--color-warning-500',
  '--color-warning-700',
  FALLBACK_VAR.error,
  '--color-error-bg',
  '--color-error-border',
  '--color-semantic-error',
  '--color-danger',
  '--color-danger-500',
  '--color-danger-text',
  '--color-danger-bg',
  '--color-danger-border',
  '--color-danger-hover',
  '--color-info',
  '--color-info-bg',
  '--color-info-border',
  ],
  border: [
  FALLBACK_VAR.borderSubtle,
  '--border-color',
  FALLBACK_VAR.borderBase,
  FALLBACK_VAR.borderMedium,
  '--border-hover',
  '--border-strong',
  '--border-prominent',
  '--border-muted',
  '--border-primary',
  '--color-border',
  '--color-border-primary',
  '--color-border-subtle',
  ],
  zIndex: [
  '--z-base',
  '--z-decoration',
  '--z-content',
  '--z-header',
  '--z-sticky',
  '--z-bottom-bar',
  '--z-floating',
  '--z-dropdown',
  '--z-overlay',
  '--z-drawer',
  '--z-modal',
  '--z-modal-active',
  '--z-fullscreen',
  '--z-toast',
  '--z-tooltip',
  '--z-popover',
  '--z-notification',
  '--z-context-menu',
  '--z-extreme',
  ],
  elementGlassShadow: [
  FALLBACK_VAR.elementBgSubtle,
  FALLBACK_VAR.elementBgSoft,
  FALLBACK_VAR.elementBgBase,
  FALLBACK_VAR.elementBgMedium,
  '--element-bg-strong',
  '--element-bg-elevated',
  '--element-bg',
  '--element-bg-hover',
  '--scrollbar-thumb',
  '--scrollbar-thumb-hover',
  '--color-scrollbar',
  '--glass-base',
  '--glass-bg-base',
  '--glass-bg-hover',
  '--glass-bg-active',
  '--glass-border-base',
  '--glass-border-hover',
  '--glass-border-focus',
  '--glass-blur-sm',
  '--glass-blur-base',
  '--glass-shadow-sm',
  '--glass-shadow-base',
  '--glass-shadow-lg',
  '--glass-shadow-xl',
  FALLBACK_VAR.shadowXs,
  FALLBACK_VAR.shadowSm,
  '--shadow-base',
  '--shadow-lg',
  '--shadow-xl',
  ],
  shapeSpacingTypography: [
  '--radius-sm',
  '--radius-base',
  '--radius-md',
  '--radius-lg',
  '--radius-xl',
  '--radius-2xl',
  '--radius-full',
  '--size-radius-sm',
  '--size-radius-base',
  '--size-radius-md',
  '--size-radius-lg',
  '--size-radius-xl',
  '--spacing-1',
  '--spacing-2',
  '--spacing-3',
  '--spacing-4',
  '--spacing-5',
  '--spacing-6',
  '--spacing-8',
  '--spacing-10',
  '--spacing-12',
  '--spacing-16',
  '--size-gap-1',
  '--size-gap-2',
  '--size-gap-3',
  '--size-gap-4',
  '--size-gap-5',
  '--size-gap-6',
  '--size-gap-8',
  '--size-gap-10',
  '--size-gap-12',
  '--size-gap-16',
  '--font-size-xxs',
  '--font-size-2xs',
  '--font-size-xs',
  '--font-size-sm',
  '--font-size-base',
  '--font-size-lg',
  '--font-size-xl',
  '--font-size-2xl',
  '--font-weight-medium',
  '--font-weight-semibold',
  '--opacity-disabled',
  '--opacity-hover',
  '--opacity-focus',
  ],
  flowChat: [
  '--flowchat-font-size-xxs',
  '--flowchat-font-size-2xs',
  '--flowchat-font-size-xs',
  '--flowchat-font-size-sm',
  '--flowchat-font-size-base',
  '--flowchat-font-size-lg',
  '--flowchat-font-size-xl',
  '--flowchat-font-size-2xl',
  '--flowchat-font-size-3xl',
  '--flowchat-font-size-4xl',
  '--flowchat-font-size-5xl',
  '--flowchat-text-line-height',
  '--flowchat-support-line-height',
  '--flowchat-compact-line-height',
  '--flowchat-flow-item-gap',
  '--flowchat-inline-gap',
  '--flowchat-control-gap',
  '--flowchat-control-pad-y',
  '--flowchat-control-pad-x',
  '--flowchat-card-gap',
  '--flowchat-card-radius',
  '--flowchat-card-pad-y',
  '--flowchat-card-pad-x',
  '--flowchat-card-tight-pad-y',
  '--flowchat-card-tight-pad-x',
  '--flowchat-card-header-pad-y',
  '--flowchat-card-header-pad-x',
  '--flowchat-card-header-pad-right',
  '--flowchat-card-expanded-pad-y',
  '--flowchat-card-expanded-pad-x',
  '--flowchat-code-font-size',
  '--flowchat-code-line-height',
  '--flowchat-code-block-pad-y',
  '--flowchat-code-block-pad-x',
  '--flowchat-markdown-block-gap',
  '--flowchat-markdown-paragraph-gap',
  '--flowchat-markdown-list-item-gap',
  '--flowchat-markdown-list-nested-gap',
  '--flowchat-markdown-heading-gap-before',
  '--flowchat-markdown-heading-gap-after',
  '--flowchat-markdown-code-block-gap',
  '--flowchat-markdown-code-block-pad-y',
  '--flowchat-markdown-code-block-pad-x',
  '--flowchat-markdown-table-cell-pad-y',
  '--flowchat-markdown-table-cell-pad-x',
  ],
  navigation: [
  '--bitfun-nav-row-action-size',
  '--bitfun-nav-row-action-icon-size',
  '--bitfun-nav-row-action-offset',
  '--bitfun-nav-row-action-gap',
  ],
  motionAndFonts: [
  '--motion-fast',
  '--motion-normal',
  '--motion-base',
  '--motion-slow',
  '--smooth-height-collapse-duration',
  '--easing-standard',
  '--font-family-sans',
  '--font-family-mono',
  '--font-sans',
  '--font-mono',
  '--markdown-font-mono',
  '--tool-card-font-mono',
  '--tool-compact-summary-font',
  ],
  buttons: [
  '--btn-primary-bg',
  '--btn-primary-color',
  '--btn-primary-border',
  '--btn-primary-shadow',
  '--btn-primary-hover-bg',
  '--btn-primary-hover-color',
  '--btn-primary-hover-border',
  '--btn-primary-hover-shadow',
  '--btn-primary-hover-transform',
  '--btn-primary-active-bg',
  '--btn-primary-active-color',
  '--btn-primary-active-border',
  '--btn-primary-active-shadow',
  '--btn-primary-active-transform',
  '--btn-ghost-bg',
  '--btn-ghost-color',
  '--btn-ghost-border',
  '--btn-ghost-shadow',
  '--btn-ghost-hover-bg',
  '--btn-ghost-hover-color',
  '--btn-ghost-hover-border',
  '--btn-ghost-hover-shadow',
  '--btn-ghost-hover-transform',
  '--btn-ghost-active-bg',
  '--btn-ghost-active-color',
  '--btn-ghost-active-border',
  '--btn-ghost-active-shadow',
  '--btn-ghost-active-transform',
  ],
  toolCard: [
  '--tool-card-bg-primary',
  '--tool-card-bg-secondary',
  '--tool-card-bg-hover',
  '--tool-card-bg-elevated',
  '--tool-card-border',
  '--tool-card-border-subtle',
  '--tool-card-text-primary',
  '--tool-card-text-secondary',
  '--tool-card-text-muted',
  '--tool-card-header-pad-y',
  '--tool-card-header-pad-x',
  '--tool-card-header-pad-right',
  '--tool-card-header-icon-rail',
  '--tool-card-header-icon-slot',
  '--tool-card-icon-size',
  '--tool-card-expanded-pad-y',
  '--tool-card-expanded-pad-x',
  '--tool-card-action-font-size',
  '--tool-card-action-line-height',
  '--tool-card-action-font-weight',
  ],
} as const;

const WIDGET_THEME_VAR_NAMES = Object.values(WIDGET_THEME_VAR_GROUPS).flat();

export function readWidgetThemePayload(): WidgetThemePayload | null {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    return null;
  }

  const root = document.documentElement;
  const styles = window.getComputedStyle(root);
  const vars: Record<string, string> = {};

  for (const name of WIDGET_THEME_VAR_NAMES) {
    const value = styles.getPropertyValue(name).trim();
    if (value) {
      vars[name] = value;
    } else if (name in WIDGET_THEME_FALLBACK_VARS) {
      vars[name] = WIDGET_THEME_FALLBACK_VARS[name as keyof typeof WIDGET_THEME_FALLBACK_VARS];
    }
  }

  return {
    id: root.getAttribute('data-theme') || 'unknown',
    type: root.getAttribute('data-theme-type') || 'dark',
    vars,
  };
}
