import { WIDGET_IFRAME_FALLBACK_COLOR } from '@/shared/theme/themeBoundaryFallbacks';

export type WidgetThemePayload = {
  id: string;
  type: string;
  vars: Record<string, string>;
};

const FALLBACK_VAR = {
  bgPrimary: '--color-bg-primary',
  bgElevated: '--color-bg-elevated',
  bgTertiary: '--color-bg-tertiary',
  bgScene: '--color-bg-scene',
  textPrimary: '--color-text-primary',
  textSecondary: '--color-text-secondary',
  textMuted: '--color-text-muted',
  textDisabled: '--color-text-disabled',
  accent50: '--color-accent-50',
  accent100: '--color-accent-100',
  accent400: '--color-accent-400',
  accent500: '--color-accent-500',
  accent500Rgb: '--color-accent-500-rgb',
  accent600: '--color-accent-600',
  bgSecondary: '--color-bg-secondary',
  success: '--color-success',
  successBg: '--color-success-bg',
  warning: '--color-warning',
  warningBg: '--color-warning-bg',
  error: '--color-error',
  errorBg: '--color-error-bg',
  errorBorder: '--color-error-border',
  staticWhite: '--color-static-white',
  overlayWhite04: '--color-overlay-white-04',
  borderSubtle: '--border-subtle',
  borderBase: '--border-base',
  borderMedium: '--border-medium',
  elementBgSubtle: '--element-bg-subtle',
  elementBgBase: '--element-bg-base',
  elementBgMedium: '--element-bg-medium',
  elementBgSoft: '--element-bg-soft',
  elementBgElevated: '--element-bg-elevated',
  elementBgHover: '--element-bg-hover',
  motionBase: '--motion-base',
  shadowXs: '--shadow-xs',
  shadowSm: '--shadow-sm',
  sizeRadiusSm: '--size-radius-sm',
  sizeRadiusBase: '--size-radius-base',
  sizeRadiusMd: '--size-radius-md',
  sizeRadiusLg: '--size-radius-lg',
  sizeRadiusXl: '--size-radius-xl',
  sizeRadius2xl: '--size-radius-2xl',
  sizeRadiusFull: '--size-radius-full',
  sizeGap1: '--size-gap-1',
  sizeGap2: '--size-gap-2',
  sizeGap3: '--size-gap-3',
  sizeGap4: '--size-gap-4',
  sizeGap5: '--size-gap-5',
  sizeGap6: '--size-gap-6',
  sizeGap8: '--size-gap-8',
  sizeGap10: '--size-gap-10',
  sizeGap12: '--size-gap-12',
  sizeGap16: '--size-gap-16',
} as const;

type WidgetThemeFallbackVarName = typeof FALLBACK_VAR[keyof typeof FALLBACK_VAR];
const widgetVar = (name: WidgetThemeFallbackVarName): string => `var(${name})`;

// Keep this fallback map small and self-contained. It is the last-resort iframe
// contract for static widget rendering before the host theme payload arrives.
export const WIDGET_THEME_FALLBACK_VARS = {
  [FALLBACK_VAR.bgPrimary]: 'transparent',
  [FALLBACK_VAR.bgElevated]: WIDGET_IFRAME_FALLBACK_COLOR.bgSecondary,
  [FALLBACK_VAR.bgTertiary]: WIDGET_IFRAME_FALLBACK_COLOR.bgSecondary,
  [FALLBACK_VAR.bgScene]: WIDGET_IFRAME_FALLBACK_COLOR.bgSecondary,
  [FALLBACK_VAR.textPrimary]: WIDGET_IFRAME_FALLBACK_COLOR.textPrimary,
  [FALLBACK_VAR.textSecondary]: WIDGET_IFRAME_FALLBACK_COLOR.textSecondary,
  [FALLBACK_VAR.textMuted]: WIDGET_IFRAME_FALLBACK_COLOR.textMuted,
  [FALLBACK_VAR.textDisabled]: WIDGET_IFRAME_FALLBACK_COLOR.textMuted,
  [FALLBACK_VAR.accent50]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.accent500)} 10%, transparent)`,
  [FALLBACK_VAR.accent100]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.accent500)} 16%, transparent)`,
  [FALLBACK_VAR.accent400]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.accent500)} 78%, ${widgetVar(FALLBACK_VAR.staticWhite)})`,
  [FALLBACK_VAR.accent500]: WIDGET_IFRAME_FALLBACK_COLOR.accent500,
  [FALLBACK_VAR.accent500Rgb]: '96 165 250',
  [FALLBACK_VAR.accent600]: WIDGET_IFRAME_FALLBACK_COLOR.accent600,
  [FALLBACK_VAR.bgSecondary]: WIDGET_IFRAME_FALLBACK_COLOR.bgSecondary,
  [FALLBACK_VAR.success]: WIDGET_IFRAME_FALLBACK_COLOR.success,
  [FALLBACK_VAR.successBg]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.success)} 16%, transparent)`,
  [FALLBACK_VAR.warning]: WIDGET_IFRAME_FALLBACK_COLOR.warning,
  [FALLBACK_VAR.warningBg]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.warning)} 16%, transparent)`,
  [FALLBACK_VAR.error]: WIDGET_IFRAME_FALLBACK_COLOR.error,
  [FALLBACK_VAR.errorBg]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.error)} 16%, transparent)`,
  [FALLBACK_VAR.errorBorder]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.error)} 34%, transparent)`,
  [FALLBACK_VAR.staticWhite]: WIDGET_IFRAME_FALLBACK_COLOR.staticWhite,
  [FALLBACK_VAR.overlayWhite04]: `color-mix(in srgb, ${widgetVar(FALLBACK_VAR.staticWhite)} 4%, transparent)`,
  [FALLBACK_VAR.borderSubtle]: WIDGET_IFRAME_FALLBACK_COLOR.borderSubtle,
  [FALLBACK_VAR.borderBase]: WIDGET_IFRAME_FALLBACK_COLOR.borderBase,
  [FALLBACK_VAR.borderMedium]: WIDGET_IFRAME_FALLBACK_COLOR.borderMedium,
  [FALLBACK_VAR.elementBgSubtle]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgSubtle,
  [FALLBACK_VAR.elementBgBase]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgBase,
  [FALLBACK_VAR.elementBgMedium]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgMedium,
  [FALLBACK_VAR.elementBgSoft]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgBase,
  [FALLBACK_VAR.elementBgElevated]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgBase,
  [FALLBACK_VAR.elementBgHover]: WIDGET_IFRAME_FALLBACK_COLOR.elementBgMedium,
  [FALLBACK_VAR.motionBase]: '0.2s',
  [FALLBACK_VAR.shadowXs]: `0 1px 2px ${WIDGET_IFRAME_FALLBACK_COLOR.shadowBase}`,
  [FALLBACK_VAR.shadowSm]: `0 2px 4px ${WIDGET_IFRAME_FALLBACK_COLOR.shadowBase}`,
  [FALLBACK_VAR.sizeRadiusSm]: '6px',
  [FALLBACK_VAR.sizeRadiusBase]: '8px',
  [FALLBACK_VAR.sizeRadiusMd]: '8px',
  [FALLBACK_VAR.sizeRadiusLg]: '12px',
  [FALLBACK_VAR.sizeRadiusXl]: '16px',
  [FALLBACK_VAR.sizeRadius2xl]: '20px',
  [FALLBACK_VAR.sizeRadiusFull]: '9999px',
  [FALLBACK_VAR.sizeGap1]: '4px',
  [FALLBACK_VAR.sizeGap2]: '8px',
  [FALLBACK_VAR.sizeGap3]: '12px',
  [FALLBACK_VAR.sizeGap4]: '16px',
  [FALLBACK_VAR.sizeGap5]: '20px',
  [FALLBACK_VAR.sizeGap6]: '24px',
  [FALLBACK_VAR.sizeGap8]: '32px',
  [FALLBACK_VAR.sizeGap10]: '40px',
  [FALLBACK_VAR.sizeGap12]: '48px',
  [FALLBACK_VAR.sizeGap16]: '64px',
} as const satisfies Record<WidgetThemeFallbackVarName, string>;

export function createWidgetThemeFallbackCss(): string {
  return Object.entries(WIDGET_THEME_FALLBACK_VARS)
    .map(([name, value]) => `      ${name}: ${value};`)
    .join('\n');
}

// Host -> generated-widget iframe theme contract. Keep groups explicit so
// isolated widgets receive stable tokens without scraping every root variable.
// Host chrome/layout internals stay private: widgets have their own stacking
// and layout context, so FlowChat, navigation, and z-index keys are not exported.
const WIDGET_THEME_VAR_GROUPS = {
  staticAndOverlay: [
  FALLBACK_VAR.bgPrimary,
  FALLBACK_VAR.staticWhite,
  '--color-static-black',
  '--color-overlay-white-02',
  FALLBACK_VAR.overlayWhite04,
  '--color-overlay-white-05',
  '--color-overlay-white-06',
  '--color-overlay-white-08',
  '--color-overlay-white-10',
  '--color-overlay-white-12',
  '--color-overlay-white-15',
  '--color-overlay-white-20',
  '--color-overlay-white-60',
  '--color-overlay-black-06',
  '--color-overlay-black-08',
  '--color-overlay-black-10',
  '--color-overlay-black-12',
  '--color-overlay-black-15',
  '--color-overlay-black-20',
  '--color-overlay-black-25',
  '--color-overlay-black-30',
  '--color-overlay-black-40',
  '--color-overlay-black-50',
  '--color-overlay-black-80',
  ],
  backgroundSurface: [
  FALLBACK_VAR.bgSecondary,
  FALLBACK_VAR.bgTertiary,
  '--color-bg-quaternary',
  FALLBACK_VAR.bgElevated,
  '--color-bg-workbench',
  FALLBACK_VAR.bgScene,
  '--color-bg-tooltip',
  ],
  text: [
  FALLBACK_VAR.textPrimary,
  FALLBACK_VAR.textSecondary,
  FALLBACK_VAR.textMuted,
  FALLBACK_VAR.textDisabled,
  ],
  accent: [
  FALLBACK_VAR.accent50,
  FALLBACK_VAR.accent100,
  '--color-accent-200',
  '--color-accent-300',
  FALLBACK_VAR.accent400,
  FALLBACK_VAR.accent500,
  FALLBACK_VAR.accent500Rgb,
  FALLBACK_VAR.accent600,
  '--color-accent-700',
  '--color-accent-800',
  ],
  semantic: [
  FALLBACK_VAR.success,
  FALLBACK_VAR.successBg,
  '--color-success-border',
  FALLBACK_VAR.warning,
  FALLBACK_VAR.warningBg,
  '--color-warning-border',
  FALLBACK_VAR.error,
  FALLBACK_VAR.errorBg,
  FALLBACK_VAR.errorBorder,
  '--color-info',
  '--color-info-bg',
  '--color-info-border',
  ],
  border: [
  FALLBACK_VAR.borderSubtle,
  FALLBACK_VAR.borderBase,
  FALLBACK_VAR.borderMedium,
  '--border-strong',
  '--border-prominent',
  ],
  elementGlassShadow: [
  FALLBACK_VAR.elementBgSubtle,
  FALLBACK_VAR.elementBgSoft,
  FALLBACK_VAR.elementBgBase,
  FALLBACK_VAR.elementBgMedium,
  '--element-bg-strong',
  FALLBACK_VAR.elementBgElevated,
  FALLBACK_VAR.elementBgHover,
  '--scrollbar-thumb',
  '--scrollbar-thumb-hover',
  '--color-scrollbar',
  '--glass-base',
  '--glass-bg-base',
  '--glass-bg-hover',
  '--glass-bg-active',
  '--glass-border-base',
  '--glass-border-hover',
  '--glass-border-focus',
  '--glass-blur-sm',
  '--glass-blur-base',
  '--glass-shadow-sm',
  '--glass-shadow-base',
  '--glass-shadow-lg',
  '--glass-shadow-xl',
  FALLBACK_VAR.shadowXs,
  FALLBACK_VAR.shadowSm,
  '--shadow-base',
  '--shadow-lg',
  '--shadow-xl',
  ],
  shapeSpacingTypography: [
  FALLBACK_VAR.sizeRadiusSm,
  FALLBACK_VAR.sizeRadiusBase,
  FALLBACK_VAR.sizeRadiusMd,
  FALLBACK_VAR.sizeRadiusLg,
  FALLBACK_VAR.sizeRadiusXl,
  FALLBACK_VAR.sizeRadius2xl,
  FALLBACK_VAR.sizeRadiusFull,
  FALLBACK_VAR.sizeGap1,
  FALLBACK_VAR.sizeGap2,
  FALLBACK_VAR.sizeGap3,
  FALLBACK_VAR.sizeGap4,
  FALLBACK_VAR.sizeGap5,
  FALLBACK_VAR.sizeGap6,
  FALLBACK_VAR.sizeGap8,
  FALLBACK_VAR.sizeGap10,
  FALLBACK_VAR.sizeGap12,
  FALLBACK_VAR.sizeGap16,
  '--font-size-xxs',
  '--font-size-2xs',
  '--font-size-xs',
  '--font-size-sm',
  '--font-size-base',
  '--font-size-lg',
  '--font-size-xl',
  '--font-size-2xl',
  '--font-weight-medium',
  '--font-weight-semibold',
  '--opacity-disabled',
  '--opacity-hover',
  '--opacity-focus',
  ],
  motionAndFonts: [
  '--motion-fast',
  FALLBACK_VAR.motionBase,
  '--motion-slow',
  '--smooth-height-collapse-duration',
  '--easing-standard',
  '--font-family-sans',
  '--font-family-mono',
  '--tool-card-font-mono',
  ],
  buttons: [
  '--btn-primary-bg',
  '--btn-primary-color',
  '--btn-primary-border',
  '--btn-primary-shadow',
  '--btn-primary-hover-bg',
  '--btn-primary-hover-color',
  '--btn-primary-hover-border',
  '--btn-primary-hover-shadow',
  '--btn-primary-hover-transform',
  '--btn-primary-active-bg',
  '--btn-primary-active-color',
  '--btn-primary-active-border',
  '--btn-primary-active-shadow',
  '--btn-primary-active-transform',
  '--btn-ghost-bg',
  '--btn-ghost-color',
  '--btn-ghost-border',
  '--btn-ghost-shadow',
  '--btn-ghost-hover-bg',
  '--btn-ghost-hover-color',
  '--btn-ghost-hover-border',
  '--btn-ghost-hover-shadow',
  '--btn-ghost-hover-transform',
  '--btn-ghost-active-bg',
  '--btn-ghost-active-color',
  '--btn-ghost-active-border',
  '--btn-ghost-active-shadow',
  '--btn-ghost-active-transform',
  ],
  toolCard: [
  '--tool-card-bg-primary',
  '--tool-card-bg-secondary',
  '--tool-card-bg-hover',
  '--tool-card-bg-elevated',
  '--tool-card-border',
  '--tool-card-border-subtle',
  '--tool-card-text-primary',
  '--tool-card-text-secondary',
  '--tool-card-text-muted',
  '--tool-card-header-pad-y',
  '--tool-card-header-pad-x',
  '--tool-card-header-pad-right',
  '--tool-card-header-icon-rail',
  '--tool-card-header-icon-slot',
  '--tool-card-icon-size',
  '--tool-card-expanded-pad-y',
  '--tool-card-expanded-pad-x',
  '--tool-card-action-font-size',
  '--tool-card-action-line-height',
  '--tool-card-action-font-weight',
  ],
} as const;

const WIDGET_THEME_VAR_NAMES = Object.values(WIDGET_THEME_VAR_GROUPS).flat();

export function readWidgetThemePayload(): WidgetThemePayload | null {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    return null;
  }

  const root = document.documentElement;
  const styles = window.getComputedStyle(root);
  const vars: Record<string, string> = {};

  for (const name of WIDGET_THEME_VAR_NAMES) {
    const value = styles.getPropertyValue(name).trim();
    if (value) {
      vars[name] = value;
    } else if (name in WIDGET_THEME_FALLBACK_VARS) {
      vars[name] = WIDGET_THEME_FALLBACK_VARS[name as keyof typeof WIDGET_THEME_FALLBACK_VARS];
    }
  }

  return {
    id: root.getAttribute('data-theme') || 'unknown',
    type: root.getAttribute('data-theme-type') || 'dark',
    vars,
  };
}
