// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit src/shared/i18n/contract/locales.json instead.
use super::types::LocaleId;

#[derive(Debug, Clone, Copy)]
pub struct GeneratedLocaleContractEntry {
    pub id: LocaleId,
    pub code: &'static str,
    pub name: &'static str,
    pub english_name: &'static str,
    pub native_name: &'static str,
    pub rtl: bool,
    pub model_language_name: &'static str,
    pub short_model_instruction: &'static str,
    pub aliases: &'static [&'static str],
    pub content_fallbacks: &'static [LocaleId],
}

pub const GENERATED_DEFAULT_LOCALE: LocaleId = LocaleId::ZhCN;
pub const GENERATED_FALLBACK_LOCALE: LocaleId = LocaleId::EnUS;
pub const GENERATED_UNKNOWN_LOCALE_FALLBACK_CHAIN: &[LocaleId] = &[LocaleId::EnUS, LocaleId::ZhCN];

pub const GENERATED_LOCALE_CONTRACT: &[GeneratedLocaleContractEntry] = &[
    GeneratedLocaleContractEntry {
        id: LocaleId::ZhCN,
        code: "zh-CN",
        name: "简体中文",
        english_name: "Simplified Chinese",
        native_name: "简体中文",
        rtl: false,
        model_language_name: "Simplified Chinese",
        short_model_instruction: "使用简体中文",
        aliases: &["zh", "zh-Hans", "zh-CN"],
        content_fallbacks: &[LocaleId::EnUS],
    },
    GeneratedLocaleContractEntry {
        id: LocaleId::ZhTW,
        code: "zh-TW",
        name: "繁體中文",
        english_name: "Traditional Chinese",
        native_name: "繁體中文",
        rtl: false,
        model_language_name: "Traditional Chinese",
        short_model_instruction: "使用繁體中文",
        aliases: &["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
        content_fallbacks: &[LocaleId::ZhCN, LocaleId::EnUS],
    },
    GeneratedLocaleContractEntry {
        id: LocaleId::EnUS,
        code: "en-US",
        name: "English",
        english_name: "English (US)",
        native_name: "English",
        rtl: false,
        model_language_name: "English",
        short_model_instruction: "Use English",
        aliases: &["en", "en-US"],
        content_fallbacks: &[LocaleId::ZhCN],
    }
];

pub fn generated_locale_entry_from_code(code: &str) -> Option<&'static GeneratedLocaleContractEntry> {
    let normalized = code.trim().to_ascii_lowercase();
    if normalized.is_empty() {
        return None;
    }

    GENERATED_LOCALE_CONTRACT
        .iter()
        .find(|entry| entry.code.eq_ignore_ascii_case(&normalized))
        .or_else(|| {
            let mut best_match = None;
            for entry in GENERATED_LOCALE_CONTRACT {
                for alias in entry.aliases {
                    let alias = alias.to_ascii_lowercase();
                    if normalized == alias || normalized.starts_with(&format!("{alias}-")) {
                        if best_match
                            .map(|(_, current_len)| alias.len() > current_len)
                            .unwrap_or(true)
                        {
                            best_match = Some((entry, alias.len()));
                        }
                    }
                }
            }
            best_match.map(|(entry, _)| entry)
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_order_matches_runtime_locale_order() {
        let generated_ids: Vec<_> = GENERATED_LOCALE_CONTRACT.iter().map(|entry| entry.id).collect();
        assert_eq!(generated_ids, LocaleId::all());
    }

    #[test]
    fn generated_contract_resolves_aliases_like_runtime_locale_contract() {
        assert_eq!(generated_locale_entry_from_code("zh-Hant-TW").map(|entry| entry.id), Some(LocaleId::ZhTW));
        assert_eq!(generated_locale_entry_from_code("  ZH-hans-CN  ").map(|entry| entry.id), Some(LocaleId::ZhCN));
        assert_eq!(generated_locale_entry_from_code("en").map(|entry| entry.id), Some(LocaleId::EnUS));
        assert_eq!(generated_locale_entry_from_code("fr-FR").map(|entry| entry.id), None);
    }
}
