// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit the shared i18n contract or shared terms instead.
export const LOCALE_IDS = ["zh-CN", "en-US", "zh-TW"] as const;
export type LocaleId = (typeof LOCALE_IDS)[number];

export const DEFAULT_LOCALE = "zh-CN" satisfies LocaleId;
export const DEFAULT_FALLBACK_LOCALE = "en-US" satisfies LocaleId;
const UNKNOWN_LOCALE_FALLBACK_CHAIN = ["en-US", "zh-CN"] as const satisfies readonly LocaleId[];

export interface LocaleMetadata {
  id: LocaleId;
  name: string;
  englishName: string;
  nativeName: string;
  shortName: string;
  rtl: boolean;
  dateFormat: string;
  numberFormat: {
    decimal: string;
    thousands: string;
  };
  aliases: readonly string[];
  contentFallbacks: readonly LocaleId[];
  builtin: boolean;
}

export type SharedI18nTerms = {
  readonly [key: string]: string | SharedI18nTerms;
};

export const SHARED_TERMS_BY_LOCALE = {
  "zh-CN": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "远程控制",
      "codeAgent": "代码助手",
      "deepReview": "严格审查",
      "settings": "设置",
      "workspace": "工作区",
      "accountLogin": "账户登录"
    },
    "modes": {
      "agentic": "代理模式",
      "assistant": "助手模式",
      "expert": "专家模式",
      "review": "评审模式"
    },
    "agents": {
      "code": "代码会话",
      "cowork": "协作会话",
      "claw": "Claw",
      "default": "默认助手"
    },
    "tools": {
      "explore": "探索",
      "read": "读取",
      "write": "写入",
      "shell": "命令行",
      "search": "搜索",
      "edit": "编辑",
      "todo": "待办"
    },
    "connectionMethods": {
      "lan": "局域网",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "自定义服务器",
      "botFeishu": "飞书机器人",
      "botTelegram": "Telegram Bot",
      "botWeixin": "微信机器人"
    },
    "statuses": {
      "loading": "加载中",
      "running": "运行中",
      "done": "已完成",
      "failed": "失败",
      "cancelled": "已取消"
    }
  },
  "en-US": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "Remote Control",
      "codeAgent": "Code Agent",
      "deepReview": "Review: Strict",
      "settings": "Settings",
      "workspace": "Workspace",
      "accountLogin": "Account Login"
    },
    "modes": {
      "agentic": "Agentic Mode",
      "assistant": "Assistant Mode",
      "expert": "Expert Mode",
      "review": "Review Mode"
    },
    "agents": {
      "code": "Code Session",
      "cowork": "Cowork Session",
      "claw": "Claw",
      "default": "Default Assistant"
    },
    "tools": {
      "explore": "Explore",
      "read": "Read",
      "write": "Write",
      "shell": "Shell",
      "search": "Search",
      "edit": "Edit",
      "todo": "Todo"
    },
    "connectionMethods": {
      "lan": "LAN",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "Custom Server",
      "botFeishu": "Feishu Bot",
      "botTelegram": "Telegram Bot",
      "botWeixin": "WeChat Bot"
    },
    "statuses": {
      "loading": "Loading",
      "running": "Running",
      "done": "Done",
      "failed": "Failed",
      "cancelled": "Cancelled"
    }
  },
  "zh-TW": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "遠端控制",
      "codeAgent": "程式碼助手",
      "deepReview": "嚴格審查",
      "settings": "設定",
      "workspace": "工作區",
      "accountLogin": "帳號登入"
    },
    "modes": {
      "agentic": "代理模式",
      "assistant": "助手模式",
      "expert": "專家模式",
      "review": "審查模式"
    },
    "agents": {
      "code": "程式碼會話",
      "cowork": "協作會話",
      "claw": "Claw",
      "default": "預設助手"
    },
    "tools": {
      "explore": "探索",
      "read": "讀取",
      "write": "寫入",
      "shell": "命令列",
      "search": "搜尋",
      "edit": "編輯",
      "todo": "待辦"
    },
    "connectionMethods": {
      "lan": "區域網路",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "自訂伺服器",
      "botFeishu": "飛書機器人",
      "botTelegram": "Telegram Bot",
      "botWeixin": "微信機器人"
    },
    "statuses": {
      "loading": "載入中",
      "running": "執行中",
      "done": "已完成",
      "failed": "失敗",
      "cancelled": "已取消"
    }
  }
} as const satisfies Record<LocaleId, SharedI18nTerms>;

export const builtinLocales = [
  {
    id: "zh-CN",
    name: "简体中文",
    englishName: "Simplified Chinese",
    nativeName: "简体中文",
    shortName: "中",
    rtl: false,
    dateFormat: "YYYY年MM月DD日",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["zh", "zh-Hans", "zh-CN"],
    contentFallbacks: ["en-US"],
    builtin: true,
  },
  {
    id: "en-US",
    name: "English",
    englishName: "English (US)",
    nativeName: "English",
    shortName: "EN",
    rtl: false,
    dateFormat: "MM/DD/YYYY",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["en", "en-US"],
    contentFallbacks: ["zh-CN"],
    builtin: true,
  },
  {
    id: "zh-TW",
    name: "繁體中文",
    englishName: "Traditional Chinese",
    nativeName: "繁體中文",
    shortName: "繁",
    rtl: false,
    dateFormat: "YYYY年MM月DD日",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
    contentFallbacks: ["zh-CN", "en-US"],
    builtin: true,
  }
] satisfies LocaleMetadata[];

const localeAliasesByPriority = builtinLocales
  .flatMap(locale => locale.aliases.map(alias => ({ locale, alias: alias.toLowerCase() })))
  .sort((a, b) => b.alias.length - a.alias.length);

export function getLocaleMetadata(localeId: LocaleId): LocaleMetadata | undefined {
  return builtinLocales.find(locale => locale.id === localeId);
}

export function resolveLocaleId(value: string | null | undefined): LocaleId | null {
  const normalized = value?.trim().toLowerCase();
  if (!normalized) return null;

  const exact = builtinLocales.find(locale => locale.id.toLowerCase() === normalized);
  if (exact) return exact.id;

  return localeAliasesByPriority
    .find(({ alias }) => normalized === alias || normalized.startsWith(`${alias}-`))
    ?.locale.id ?? null;
}

export function isLocaleSupported(localeId: string): localeId is LocaleId {
  return resolveLocaleId(localeId) === localeId;
}

export function getSupportedLocaleIds(): LocaleId[] {
  return builtinLocales.map(locale => locale.id);
}

export function getLocaleFallbackChain(localeId: string, includeSelf = false): LocaleId[] {
  const resolved = resolveLocaleId(localeId);
  const chain: LocaleId[] = resolved
    ? [
      ...(includeSelf ? [resolved] : []),
      ...(getLocaleMetadata(resolved)?.contentFallbacks ?? []),
    ]
    : [...UNKNOWN_LOCALE_FALLBACK_CHAIN];

  return Array.from(new Set(chain));
}

export const CONTRACT_LOCALE_METADATA_BY_ID = {
  "zh-CN": "Simplified Chinese",
  "en-US": "English (US)",
  "zh-TW": "Traditional Chinese"
} as const satisfies Record<LocaleId, string>;
