// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit src/shared/i18n/contract/locales.json instead.
export const LOCALE_IDS = ["zh-CN", "en-US", "zh-TW"] as const;
export type LocaleId = (typeof LOCALE_IDS)[number];

export const DEFAULT_LOCALE = "zh-CN" satisfies LocaleId;
export const DEFAULT_FALLBACK_LOCALE = "en-US" satisfies LocaleId;
const UNKNOWN_LOCALE_FALLBACK_CHAIN = ["en-US", "zh-CN"] as const satisfies readonly LocaleId[];

export interface LocaleMetadata {
  id: LocaleId;
  name: string;
  englishName: string;
  nativeName: string;
  shortName: string;
  rtl: boolean;
  dateFormat: string;
  numberFormat: {
    decimal: string;
    thousands: string;
  };
  aliases: readonly string[];
  contentFallbacks: readonly LocaleId[];
  builtin: boolean;
}

export const builtinLocales = [
  {
    id: "zh-CN",
    name: "简体中文",
    englishName: "Simplified Chinese",
    nativeName: "简体中文",
    shortName: "中",
    rtl: false,
    dateFormat: "YYYY年MM月DD日",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["zh", "zh-Hans", "zh-CN"],
    contentFallbacks: ["en-US"],
    builtin: true,
  },
  {
    id: "en-US",
    name: "English",
    englishName: "English (US)",
    nativeName: "English",
    shortName: "EN",
    rtl: false,
    dateFormat: "MM/DD/YYYY",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["en", "en-US"],
    contentFallbacks: ["zh-CN"],
    builtin: true,
  },
  {
    id: "zh-TW",
    name: "繁體中文",
    englishName: "Traditional Chinese",
    nativeName: "繁體中文",
    shortName: "繁",
    rtl: false,
    dateFormat: "YYYY年MM月DD日",
    numberFormat: {
      decimal: ".",
      thousands: ",",
    },
    aliases: ["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
    contentFallbacks: ["zh-CN", "en-US"],
    builtin: true,
  }
] satisfies LocaleMetadata[];

const localeAliasesByPriority = builtinLocales
  .flatMap(locale => locale.aliases.map(alias => ({ locale, alias: alias.toLowerCase() })))
  .sort((a, b) => b.alias.length - a.alias.length);

export function getLocaleMetadata(localeId: LocaleId): LocaleMetadata | undefined {
  return builtinLocales.find(locale => locale.id === localeId);
}

export function resolveLocaleId(value: string | null | undefined): LocaleId | null {
  const normalized = value?.trim().toLowerCase();
  if (!normalized) return null;

  const exact = builtinLocales.find(locale => locale.id.toLowerCase() === normalized);
  if (exact) return exact.id;

  return localeAliasesByPriority
    .find(({ alias }) => normalized === alias || normalized.startsWith(`${alias}-`))
    ?.locale.id ?? null;
}

export function isLocaleSupported(localeId: string): localeId is LocaleId {
  return resolveLocaleId(localeId) === localeId;
}

export function getSupportedLocaleIds(): LocaleId[] {
  return builtinLocales.map(locale => locale.id);
}

export function getLocaleFallbackChain(localeId: string, includeSelf = false): LocaleId[] {
  const resolved = resolveLocaleId(localeId);
  const chain: LocaleId[] = resolved
    ? [
      ...(includeSelf ? [resolved] : []),
      ...(getLocaleMetadata(resolved)?.contentFallbacks ?? []),
    ]
    : [...UNKNOWN_LOCALE_FALLBACK_CHAIN];

  return Array.from(new Set(chain));
}

export const CONTRACT_LOCALE_METADATA_BY_ID = {
  "zh-CN": "Simplified Chinese",
  "en-US": "English (US)",
  "zh-TW": "Traditional Chinese"
} as const satisfies Record<LocaleId, string>;
