// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit the shared i18n contract or shared terms instead.
use super::types::LocaleId;

#[derive(Debug, Clone, Copy)]
pub struct GeneratedLocaleContractEntry {
    pub id: LocaleId,
    pub code: &'static str,
    pub name: &'static str,
    pub english_name: &'static str,
    pub native_name: &'static str,
    pub rtl: bool,
    pub model_language_name: &'static str,
    pub short_model_instruction: &'static str,
    pub aliases: &'static [&'static str],
    pub content_fallbacks: &'static [LocaleId],
}

#[derive(Debug, Clone, Copy)]
pub struct GeneratedSharedTermEntry {
    pub locale: LocaleId,
    pub key: &'static str,
    pub value: &'static str,
}

pub const GENERATED_DEFAULT_LOCALE: LocaleId = LocaleId::ZhCN;
pub const GENERATED_FALLBACK_LOCALE: LocaleId = LocaleId::EnUS;
pub const GENERATED_UNKNOWN_LOCALE_FALLBACK_CHAIN: &[LocaleId] = &[LocaleId::EnUS, LocaleId::ZhCN];

pub const GENERATED_LOCALE_CONTRACT: &[GeneratedLocaleContractEntry] = &[
    GeneratedLocaleContractEntry {
        id: LocaleId::ZhCN,
        code: "zh-CN",
        name: "简体中文",
        english_name: "Simplified Chinese",
        native_name: "简体中文",
        rtl: false,
        model_language_name: "Simplified Chinese",
        short_model_instruction: "使用简体中文",
        aliases: &["zh", "zh-Hans", "zh-CN"],
        content_fallbacks: &[LocaleId::EnUS],
    },
    GeneratedLocaleContractEntry {
        id: LocaleId::ZhTW,
        code: "zh-TW",
        name: "繁體中文",
        english_name: "Traditional Chinese",
        native_name: "繁體中文",
        rtl: false,
        model_language_name: "Traditional Chinese",
        short_model_instruction: "使用繁體中文",
        aliases: &["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
        content_fallbacks: &[LocaleId::ZhCN, LocaleId::EnUS],
    },
    GeneratedLocaleContractEntry {
        id: LocaleId::EnUS,
        code: "en-US",
        name: "English",
        english_name: "English (US)",
        native_name: "English",
        rtl: false,
        model_language_name: "English",
        short_model_instruction: "Use English",
        aliases: &["en", "en-US"],
        content_fallbacks: &[LocaleId::ZhCN],
    },
];

pub const GENERATED_SHARED_TERMS: &[GeneratedSharedTermEntry] = &[
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "agents.claw",
        value: "Claw",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "agents.code",
        value: "代码会话",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "agents.cowork",
        value: "协作会话",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "agents.default",
        value: "默认助手",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.bitfunServer",
        value: "BitFun Server",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.botFeishu",
        value: "飞书机器人",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.botTelegram",
        value: "Telegram Bot",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.botWeixin",
        value: "微信机器人",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.customServer",
        value: "自定义服务器",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.lan",
        value: "局域网",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "connectionMethods.ngrok",
        value: "Ngrok",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "features.codeAgent",
        value: "代码助手",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "features.deepReview",
        value: "深度代码评审",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "features.remoteControl",
        value: "远程控制",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "features.settings",
        value: "设置",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "features.workspace",
        value: "工作区",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "modes.agentic",
        value: "代理模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "modes.assistant",
        value: "助手模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "modes.expert",
        value: "专家模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "modes.review",
        value: "评审模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "product.name",
        value: "BitFun",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "product.remote",
        value: "BitFun Remote",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "statuses.cancelled",
        value: "已取消",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "statuses.done",
        value: "已完成",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "statuses.failed",
        value: "失败",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "statuses.loading",
        value: "加载中",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "statuses.running",
        value: "运行中",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.edit",
        value: "编辑",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.explore",
        value: "探索",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.read",
        value: "读取",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.search",
        value: "搜索",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.shell",
        value: "命令行",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.todo",
        value: "待办",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhCN,
        key: "tools.write",
        value: "写入",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "agents.claw",
        value: "Claw",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "agents.code",
        value: "程式碼會話",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "agents.cowork",
        value: "協作會話",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "agents.default",
        value: "預設助手",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.bitfunServer",
        value: "BitFun Server",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.botFeishu",
        value: "飛書機器人",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.botTelegram",
        value: "Telegram Bot",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.botWeixin",
        value: "微信機器人",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.customServer",
        value: "自訂伺服器",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.lan",
        value: "區域網路",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "connectionMethods.ngrok",
        value: "Ngrok",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "features.codeAgent",
        value: "程式碼助手",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "features.deepReview",
        value: "深度程式碼審查",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "features.remoteControl",
        value: "遠端控制",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "features.settings",
        value: "設定",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "features.workspace",
        value: "工作區",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "modes.agentic",
        value: "代理模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "modes.assistant",
        value: "助手模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "modes.expert",
        value: "專家模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "modes.review",
        value: "審查模式",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "product.name",
        value: "BitFun",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "product.remote",
        value: "BitFun Remote",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "statuses.cancelled",
        value: "已取消",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "statuses.done",
        value: "已完成",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "statuses.failed",
        value: "失敗",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "statuses.loading",
        value: "載入中",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "statuses.running",
        value: "執行中",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.edit",
        value: "編輯",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.explore",
        value: "探索",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.read",
        value: "讀取",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.search",
        value: "搜尋",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.shell",
        value: "命令列",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.todo",
        value: "待辦",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::ZhTW,
        key: "tools.write",
        value: "寫入",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "agents.claw",
        value: "Claw",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "agents.code",
        value: "Code Session",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "agents.cowork",
        value: "Cowork Session",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "agents.default",
        value: "Default Assistant",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.bitfunServer",
        value: "BitFun Server",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.botFeishu",
        value: "Feishu Bot",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.botTelegram",
        value: "Telegram Bot",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.botWeixin",
        value: "WeChat Bot",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.customServer",
        value: "Custom Server",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.lan",
        value: "LAN",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "connectionMethods.ngrok",
        value: "Ngrok",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "features.codeAgent",
        value: "Code Agent",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "features.deepReview",
        value: "Deep Review",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "features.remoteControl",
        value: "Remote Control",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "features.settings",
        value: "Settings",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "features.workspace",
        value: "Workspace",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "modes.agentic",
        value: "Agentic Mode",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "modes.assistant",
        value: "Assistant Mode",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "modes.expert",
        value: "Expert Mode",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "modes.review",
        value: "Review Mode",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "product.name",
        value: "BitFun",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "product.remote",
        value: "BitFun Remote",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "statuses.cancelled",
        value: "Cancelled",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "statuses.done",
        value: "Done",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "statuses.failed",
        value: "Failed",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "statuses.loading",
        value: "Loading",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "statuses.running",
        value: "Running",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.edit",
        value: "Edit",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.explore",
        value: "Explore",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.read",
        value: "Read",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.search",
        value: "Search",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.shell",
        value: "Shell",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.todo",
        value: "Todo",
    },
    GeneratedSharedTermEntry {
        locale: LocaleId::EnUS,
        key: "tools.write",
        value: "Write",
    },
];

pub fn generated_locale_entry(id: LocaleId) -> &'static GeneratedLocaleContractEntry {
    GENERATED_LOCALE_CONTRACT
        .iter()
        .find(|entry| entry.id == id)
        .expect("LocaleId missing from generated locale contract")
}

pub fn generated_locale_entry_from_code(
    code: &str,
) -> Option<&'static GeneratedLocaleContractEntry> {
    let normalized = code.trim().to_ascii_lowercase();
    if normalized.is_empty() {
        return None;
    }

    GENERATED_LOCALE_CONTRACT
        .iter()
        .find(|entry| entry.code.eq_ignore_ascii_case(&normalized))
        .or_else(|| {
            let mut best_match = None;
            for entry in GENERATED_LOCALE_CONTRACT {
                for alias in entry.aliases {
                    let alias = alias.to_ascii_lowercase();
                    if normalized == alias || normalized.starts_with(&format!("{alias}-")) {
                        if best_match
                            .map(|(_, current_len)| alias.len() > current_len)
                            .unwrap_or(true)
                        {
                            best_match = Some((entry, alias.len()));
                        }
                    }
                }
            }
            best_match.map(|(entry, _)| entry)
        })
}

pub fn generated_shared_term(locale: LocaleId, key: &str) -> Option<&'static str> {
    GENERATED_SHARED_TERMS
        .iter()
        .find(|entry| entry.locale == locale && entry.key == key)
        .map(|entry| entry.value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_order_matches_runtime_locale_order() {
        let generated_ids: Vec<_> = GENERATED_LOCALE_CONTRACT
            .iter()
            .map(|entry| entry.id)
            .collect();
        assert_eq!(generated_ids, LocaleId::all());
    }

    #[test]
    fn generated_contract_resolves_aliases_like_runtime_locale_contract() {
        assert_eq!(
            generated_locale_entry_from_code("zh-Hant-TW").map(|entry| entry.id),
            Some(LocaleId::ZhTW)
        );
        assert_eq!(
            generated_locale_entry_from_code("  ZH-hans-CN  ").map(|entry| entry.id),
            Some(LocaleId::ZhCN)
        );
        assert_eq!(
            generated_locale_entry_from_code("en").map(|entry| entry.id),
            Some(LocaleId::EnUS)
        );
        assert_eq!(
            generated_locale_entry_from_code("fr-FR").map(|entry| entry.id),
            None
        );
    }

    #[test]
    fn generated_contract_contains_shared_terms() {
        assert_eq!(
            generated_shared_term(LocaleId::EnUS, "features.deepReview"),
            Some("Deep Review")
        );
    }
}
