import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const contractPath = path.join(root, 'src', 'shared', 'i18n', 'contract', 'locales.json');
const sharedTermsDir = path.join(root, 'src', 'shared', 'i18n', 'resources', 'shared');
const expectedGeneratedFiles = [
  'src/web-ui/src/infrastructure/i18n/presets/generatedLocaleContract.ts',
  'src/mobile-web/src/i18n/generatedLocaleContract.ts',
  'BitFun-Installer/src/i18n/generatedLocaleContract.ts',
  'src/crates/core/src/service/i18n/generated_locale_contract.rs',
  'BitFun-Installer/src-tauri/src/installer/generated_locale_contract.rs',
];

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8'));
}

function readText(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function writeText(relativePath, content) {
  fs.mkdirSync(path.dirname(path.join(root, relativePath)), { recursive: true });
  fs.writeFileSync(path.join(root, relativePath), content, 'utf8');
}

function runI18nAudit() {
  return spawnSync(process.execPath, ['scripts/i18n-audit.mjs'], {
    cwd: root,
    encoding: 'utf8',
  });
}

function withTemporaryTextFile(relativePath, content, callback) {
  const absolutePath = path.join(root, relativePath);
  const existed = fs.existsSync(absolutePath);
  const previous = existed ? fs.readFileSync(absolutePath, 'utf8') : null;

  writeText(relativePath, content);
  try {
    return callback();
  } finally {
    if (existed) {
      fs.writeFileSync(absolutePath, previous, 'utf8');
    } else {
      fs.rmSync(absolutePath, { force: true });
    }
  }
}

function flattenKeys(value, prefix = '') {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    return prefix ? [prefix] : [];
  }

  return Object.entries(value)
    .flatMap(([key, child]) => flattenKeys(child, prefix ? `${prefix}.${key}` : key))
    .sort();
}

function listFiles(dir, predicate) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return listFiles(absolutePath, predicate);
    }

    return predicate(absolutePath) ? [absolutePath] : [];
  });
}

function extractStringArrayConstant(source, exportName) {
  const marker = `export const ${exportName} = [`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `missing ${exportName} constant`);
  const body = source.slice(start + marker.length);
  const end = body.indexOf('] as const');
  assert.notEqual(end, -1, `${exportName} must be an as const string array`);
  return [...body.slice(0, end).matchAll(/'([^']+)'/g)].map((entry) => entry[1]);
}

test('i18n contract generated files are in sync with the canonical contract', () => {
  assert.ok(fs.existsSync(contractPath), 'missing shared i18n locale contract');

  const contract = readJson('src/shared/i18n/contract/locales.json');
  assert.deepEqual(
    contract.locales.map((locale) => locale.id),
    ['zh-CN', 'en-US', 'zh-TW'],
  );

  for (const relativePath of expectedGeneratedFiles) {
    const absolutePath = path.join(root, relativePath);
    assert.ok(fs.existsSync(absolutePath), `missing generated contract file: ${relativePath}`);
    assert.match(fs.readFileSync(absolutePath, 'utf8'), /generated by scripts\/generate-i18n-contract\.mjs/);
  }

  execFileSync(process.execPath, ['scripts/generate-i18n-contract.mjs', '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});

test('shared i18n terms exist for every canonical locale with matching keys', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const expectedLocaleIds = contract.locales.map((locale) => locale.id);

  assert.ok(fs.existsSync(sharedTermsDir), 'missing shared i18n terms directory');

  const baseline = readJson(`src/shared/i18n/resources/shared/${expectedLocaleIds[0]}/terms.json`);
  const baselineKeys = flattenKeys(baseline);

  for (const localeId of expectedLocaleIds) {
    const relativePath = `src/shared/i18n/resources/shared/${localeId}/terms.json`;
    const terms = readJson(relativePath);
    assert.deepEqual(flattenKeys(terms), baselineKeys, `${relativePath} key set differs from baseline`);
  }
});

test('core runtime uses the generated locale contract for language identity', () => {
  const typesSource = readText('src/crates/core/src/service/i18n/types.rs');
  assert.match(
    typesSource,
    /generated_locale_contract::\{[\s\S]*GENERATED_LOCALE_CONTRACT/,
    'LocaleId and LocaleMetadata should derive identity fields from the generated contract',
  );
  assert.doesNotMatch(
    typesSource,
    /locale_registry::\{[\s\S]*(LOCALE_REGISTRY|locale_entry|locale_entry_from_code)/,
    'types.rs must not read language identity from the backend resource registry',
  );

  const resourceRegistrySource = readText('src/crates/core/src/service/i18n/locale_registry.rs');
  assert.doesNotMatch(
    resourceRegistrySource,
    /\b(name|english_name|native_name|rtl|model_language_name|short_model_instruction|aliases):/,
    'backend locale_registry.rs should only own Fluent resource wiring, not duplicate locale identity',
  );
});

test('shared i18n terms are consumed by each product surface runtime', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /SHARED_TERMS_BY_LOCALE/, 'Web UI should merge shared terms into i18next resources');

  const mobileMessagesSource = readText('src/mobile-web/src/i18n/messages.ts');
  assert.match(mobileMessagesSource, /SHARED_TERMS_BY_LOCALE/, 'mobile-web should expose shared terms through its message tree');

  const installerLanguagesSource = readText('BitFun-Installer/src/i18n/languages.ts');
  assert.match(installerLanguagesSource, /SHARED_TERMS_BY_APP_LANGUAGE/, 'installer should merge shared terms into its i18next resources');

  const coreServiceSource = readText('src/crates/core/src/service/i18n/service.rs');
  assert.match(coreServiceSource, /generated_shared_term/, 'core i18n service should resolve generated shared terms');
});

test('frontend runtimes use generated locale defaults and fallback chains', () => {
  const webPresetIndexSource = readText('src/web-ui/src/infrastructure/i18n/presets/index.ts');
  assert.doesNotMatch(
    webPresetIndexSource,
    /export const DEFAULT_(?:FALLBACK_)?LOCALE\s*=\s*['"]/,
    'Web UI preset defaults should be re-exported from the generated contract, not hard-coded',
  );

  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /getLocaleFallbackChain/, 'Web UI i18next should use the generated locale fallback chain');

  const mobileProviderSource = readText('src/mobile-web/src/i18n/I18nProvider.tsx');
  assert.match(mobileProviderSource, /getMobileFallbackChain/, 'mobile-web translate should use the generated locale fallback chain');
  assert.doesNotMatch(
    mobileProviderSource,
    /messages\[DEFAULT_LANGUAGE\]/,
    'mobile-web translate should not fall back directly to the surface default only',
  );

  const installerI18nSource = readText('BitFun-Installer/src/i18n/index.ts');
  assert.match(installerI18nSource, /DEFAULT_INSTALLER_UI_LANGUAGE/, 'installer i18next should use the generated default UI language');
  assert.match(installerI18nSource, /getInstallerUiFallbackChain/, 'installer i18next should use the generated locale fallback chain');
});

test('web-ui runtime keeps locale namespaces lazy outside its bootstrap set', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');

  assert.match(webI18nSource, /WEB_UI_BOOTSTRAP_NAMESPACES/, 'Web UI should declare the small eager namespace set');
  assert.match(webI18nSource, /import\.meta\.glob\('\.\.\/\.\.\/\.\.\/locales\/\*\*\/\*\.json'/, 'Web UI should keep a lazy namespace glob for non-bootstrap resources');
  const lazyGlobBlock = webI18nSource.match(/const lazyLocaleModules = import\.meta\.glob\([\s\S]*?\) as/)?.[0] ?? '';
  assert.doesNotMatch(
    lazyGlobBlock,
    /eager:\s*true/,
    'Web UI must not eagerly import every locale namespace',
  );
});

test('web-ui synchronous i18nService.t namespaces stay in the bootstrap set', () => {
  const registrySource = readText('src/web-ui/src/infrastructure/i18n/presets/namespaceRegistry.ts');
  const bootstrapNamespaces = new Set(extractStringArrayConstant(registrySource, 'WEB_UI_BOOTSTRAP_NAMESPACES'));
  const sourceRoot = path.join(root, 'src', 'web-ui', 'src');
  const missing = new Set();

  const sourceFiles = listFiles(sourceRoot, (file) => {
    const normalized = file.replace(/\\/g, '/');
    return (
      /\.(ts|tsx)$/.test(file) &&
      !normalized.includes('/locales/') &&
      !normalized.endsWith('.test.ts') &&
      !normalized.endsWith('.test.tsx') &&
      !normalized.endsWith('.spec.ts') &&
      !normalized.endsWith('.spec.tsx')
    );
  });

  for (const file of sourceFiles) {
    const text = fs.readFileSync(file, 'utf8');
    const patterns = [/i18nService\.t\(\s*(['"`])([^'"`:]+):/g];
    if (text.includes('i18nService.getT()')) {
      patterns.push(/\bt\(\s*(['"`])([^'"`:]+):/g);
    }

    for (const pattern of patterns) {
      for (const match of text.matchAll(pattern)) {
        const namespace = match[2];
        if (!bootstrapNamespaces.has(namespace)) {
          missing.add(`${namespace} (${path.relative(root, file).replace(/\\/g, '/')})`);
        }
      }
    }
  }

  assert.deepEqual(
    [...missing].sort(),
    [],
    'synchronous i18nService.t(...) call sites require eager bootstrap namespaces',
  );
});

test('i18n audit enforces the checked-in hardcoded source candidate budget', () => {
  const baselineSource = readText('scripts/i18n-hardcoded-baseline.json');
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.doesNotThrow(() => JSON.parse(baselineSource));
  assert.match(auditSource, /i18n-hardcoded-baseline\.json/, 'i18n:audit should read the hardcoded copy baseline');
  assert.match(auditSource, /auditHardcodedSourceBudgets/, 'i18n:audit should fail when hardcoded candidate budgets grow');
});

test('i18n audit treats locale key parity as an error', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const parityFunction = auditSource.match(/function auditKeyParity\(namespaces\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json is missing/, 'missing locale keys should fail i18n:audit');
  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json has/, 'extra locale keys should fail i18n:audit');
  assert.match(auditSource, /auditMobileWebMessageParity/, 'mobile-web message keys should be covered by i18n:audit');
  assert.match(auditSource, /auditInstallerKeyParity/, 'installer locale keys should be covered by i18n:audit');
});

test('CI runs i18n contract and audit guards before frontend builds', () => {
  const ciSource = readText('.github/workflows/ci.yml');
  const contractIndex = ciSource.indexOf('pnpm run i18n:contract:test');
  const auditIndex = ciSource.indexOf('pnpm run i18n:audit');
  const buildIndex = ciSource.indexOf('pnpm run build:web');

  assert.notEqual(contractIndex, -1, 'CI should run pnpm run i18n:contract:test');
  assert.notEqual(auditIndex, -1, 'CI should run pnpm run i18n:audit');
  assert.ok(contractIndex < buildIndex, 'i18n contract checks should run before web build');
  assert.ok(auditIndex < buildIndex, 'i18n audit should run before web build');
});

test('i18n audit enforces interpolation parameter parity across resource formats', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /auditWebI18nextPlaceholderParity/, 'Web UI JSON placeholders should be audited');
  assert.match(auditSource, /auditMobileWebPlaceholderParity/, 'mobile-web placeholders should be audited');
  assert.match(auditSource, /auditInstallerPlaceholderParity/, 'installer placeholders should be audited');
  assert.match(auditSource, /auditCoreFluentParity/, 'core Fluent keys and placeholders should be audited');
  assert.match(auditSource, /auditRelayStaticHomepageResources/, 'relay static homepage resources should be audited');
  assert.match(auditSource, /extractI18nextPlaceholders/, 'i18next placeholder extraction should be explicit');
  assert.match(auditSource, /extractMobilePlaceholders/, 'mobile placeholder extraction should be explicit');
  assert.match(auditSource, /extractFluentPlaceholders/, 'Fluent placeholder extraction should be explicit');
});

test('i18n audit fails literal fallbacks and unknown static keys', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const sourceTextAudit = auditSource.match(/function auditSourceText\(\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(sourceTextAudit, /reportError/, 'literal t(key, "fallback") candidates should fail audit');
  assert.match(auditSource, /auditWebUiStaticTranslationKeys/, 'static Web UI translation keys should be checked');
  assert.match(auditSource, /collectWebUiStaticTranslationKeys/, 'static key collection should be explicit');
});

test('i18n audit gates object-form literal fallbacks with an explicit budget', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const fallbackBaselineSource = readText('scripts/i18n-literal-fallback-baseline.json');
  const fallbackBaseline = JSON.parse(fallbackBaselineSource);

  assert.ok(
    fallbackBaseline.budgets.every((entry) => (
      entry.literalDefaultValues &&
      typeof entry.literalDefaultValues === 'object' &&
      !Array.isArray(entry.literalDefaultValues)
    )),
    'literal fallback baseline should allowlist exact keys per file',
  );
  assert.match(auditSource, /i18n-literal-fallback-baseline\.json/, 'audit should read the literal fallback baseline');
  assert.match(auditSource, /auditWebUiLiteralFallbackBudget/, 'object-form defaultValue fallbacks should have a no-growth gate');
  assert.match(auditSource, /defaultValue/, 'audit should inspect i18next defaultValue options');
});

test('i18n audit validates static hook translation keys with namespace context', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /use(?:I18n|Translation)/, 'audit should inspect hook namespace declarations');
  assert.match(auditSource, /hookNamespaceByTranslator/, 'audit should remember namespace aliases returned by hooks');
  assert.match(auditSource, /relative static Web UI i18n key/, 'audit should report missing relative hook keys clearly');
});

test('i18n audit catches array-namespace keys and stale literal fallback budgets', { concurrency: false }, () => {
  const arrayNamespaceFixture = 'src/web-ui/src/__i18n_array_namespace_audit_fixture__.tsx';
  const missingFullKey = 'components:__arrayNamespaceAuditMissingKey__';
  const missingRelativeKey = 'components:__arrayNamespaceAuditMissingRelativeKey__';
  const missingUseTranslationKey = 'common:__arrayNamespaceUseTranslationMissingKey__';

  withTemporaryTextFile(
    arrayNamespaceFixture,
    [
      "import { useI18n, useTranslation } from '@/infrastructure/i18n';",
      'export function I18nArrayNamespaceAuditFixture() {',
      "  const { t } = useI18n(['components', 'common', 'errors']);",
      "  const [translate] = useTranslation(['common', 'errors']);",
      `  return <div>{t('${missingFullKey}')}{t('__arrayNamespaceAuditMissingRelativeKey__')}{translate('${missingUseTranslationKey}')}</div>;`,
      '}',
      '',
    ].join('\n'),
    () => {
      const result = runI18nAudit();
      assert.notEqual(result.status, 0, 'array namespace full keys must be included in unknown-key audit');
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingFullKey),
        'audit output should identify the missing array-namespace key',
      );
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingRelativeKey),
        'audit output should resolve relative array-namespace keys against the first namespace',
      );
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingUseTranslationKey),
        'audit output should cover useTranslation array namespace aliases',
      );
    },
  );

  const baselinePath = 'scripts/i18n-literal-fallback-baseline.json';
  const baseline = readJson(baselinePath);
  baseline.budgets.push({
    path: 'src/web-ui/src/__removed_literal_fallback_fixture__.tsx',
    literalDefaultValues: {
      'common:actions.close': 1,
    },
  });

  withTemporaryTextFile(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale literal fallback baseline entries must fail audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /no longer has literal i18next defaultValue fallback/,
      'audit output should explain the stale literal fallback budget',
    );
  });
});

test('i18n generation checks are stable across line endings', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');

  assert.match(generatorSource, /normalizeGeneratedText/, 'generated contract check should normalize line endings');
  assert.match(generatorSource, /currentContentForCheck/, 'generated contract check should compare normalized current content');
});

test('i18n audit preflights TypeScript before TypeScript-backed checks', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /loadTypeScriptForAudit/, 'audit should load TypeScript through a single preflight helper');
  assert.match(auditSource, /Run pnpm install/, 'missing TypeScript should tell contributors how to fix the local setup');
});

test('installer Rust locale contract is generated from the installer surface order', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');
  const installerRustGenerator = generatorSource.match(/function generateInstallerRustLocaleContract\(contract\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(installerRustGenerator, /orderedLocales\(contract, 'installer'\)/);
  assert.doesNotMatch(installerRustGenerator, /orderedLocales\(contract, 'core'\)/);
});

test('i18n contract surface resource roots point at existing owned resources', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const localeById = new Map(contract.locales.map((locale) => [locale.id, locale]));

  for (const [surface, config] of Object.entries(contract.surfaces)) {
    const resourceRoot = path.join(root, config.resourceRoot);
    assert.ok(fs.existsSync(resourceRoot), `${surface} resourceRoot does not exist: ${config.resourceRoot}`);

    for (const localeId of contract.surfaceOrders[surface] ?? []) {
      if (surface === 'web-ui') {
        assert.ok(fs.existsSync(path.join(resourceRoot, localeId)), `${surface} is missing ${localeId} locale directory`);
      } else if (surface === 'installer') {
        const locale = localeById.get(localeId);
        assert.ok(locale?.installer?.uiCode, `${localeId} is missing installer.uiCode`);
        assert.ok(fs.existsSync(path.join(resourceRoot, `${locale.installer.uiCode}.json`)), `${surface} is missing ${localeId} resource JSON`);
      } else if (surface === 'core') {
        assert.ok(fs.existsSync(path.join(resourceRoot, `${localeId}.ftl`)), `${surface} is missing ${localeId} Fluent resource`);
      } else if (surface === 'mobile-web') {
        assert.ok(fs.existsSync(path.join(resourceRoot, 'messages.ts')), `${surface} is missing messages.ts`);
      }
    }
  }
});
