import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const contractTestProfile = process.env.BITFUN_I18N_CONTRACT_TEST_PROFILE ?? 'full';
const runAuditIntegrationTests = process.env.BITFUN_I18N_CONTRACT_TEST_AUDIT_INTEGRATION === '1';
const skipAuditIntegrationTests = contractTestProfile === 'ci' && !runAuditIntegrationTests;
const contractPath = path.join(root, 'src', 'shared', 'i18n', 'contract', 'locales.json');
const sharedTermsDir = path.join(root, 'src', 'shared', 'i18n', 'resources', 'shared');
const expectedGeneratedFiles = [
  'src/web-ui/src/infrastructure/i18n/presets/generatedLocaleContract.ts',
  'src/mobile-web/src/i18n/generatedLocaleContract.ts',
  'BitFun-Installer/src/i18n/generatedLocaleContract.ts',
  'src/crates/assembly/core/src/service/i18n/generated_locale_contract.rs',
  'BitFun-Installer/src-tauri/src/installer/generated_locale_contract.rs',
];
const expectedGeneratedJsonFiles = [
  'src/apps/relay-server/static/homepage/i18n.shared.json',
];

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8'));
}

function readText(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function writeText(relativePath, content) {
  fs.mkdirSync(path.dirname(path.join(root, relativePath)), { recursive: true });
  fs.writeFileSync(path.join(root, relativePath), content, 'utf8');
}

function runI18nAudit(args = []) {
  return spawnSync(process.execPath, ['scripts/i18n-audit.mjs', ...args], {
    cwd: root,
    encoding: 'utf8',
  });
}

// CI runs one full i18n:audit immediately after this file; keep mutation-heavy
// audit integration cases in the default profile without paying that cost twice.
function auditIntegrationTest(name, optionsOrFn, maybeFn) {
  const runner = skipAuditIntegrationTests ? test.skip : test;
  if (typeof optionsOrFn === 'function') {
    return runner(name, optionsOrFn);
  }

  return runner(name, optionsOrFn, maybeFn);
}

function withTemporaryTextFile(relativePath, content, callback) {
  const absolutePath = path.join(root, relativePath);
  const existed = fs.existsSync(absolutePath);
  const previous = existed ? fs.readFileSync(absolutePath, 'utf8') : null;

  writeText(relativePath, content);
  try {
    return callback();
  } finally {
    if (existed) {
      fs.writeFileSync(absolutePath, previous, 'utf8');
    } else {
      fs.rmSync(absolutePath, { force: true });
    }
  }
}

function flattenKeys(value, prefix = '') {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    return prefix ? [prefix] : [];
  }

  return Object.entries(value)
    .flatMap(([key, child]) => flattenKeys(child, prefix ? `${prefix}.${key}` : key))
    .sort();
}

function getValueByPath(value, dottedPath) {
  return dottedPath.split('.').reduce((current, segment) => (
    current && typeof current === 'object' ? current[segment] : undefined
  ), value);
}

function listFiles(dir, predicate) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return listFiles(absolutePath, predicate);
    }

    return predicate(absolutePath) ? [absolutePath] : [];
  });
}

function extractStringArrayConstant(source, exportName) {
  const marker = `export const ${exportName} = [`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `missing ${exportName} constant`);
  const body = source.slice(start + marker.length);
  const end = body.indexOf('] as const');
  assert.notEqual(end, -1, `${exportName} must be an as const string array`);
  return [...body.slice(0, end).matchAll(/'([^']+)'/g)].map((entry) => entry[1]);
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

test('i18n contract generated files are in sync with the canonical contract', () => {
  assert.ok(fs.existsSync(contractPath), 'missing shared i18n locale contract');

  const contract = readJson('src/shared/i18n/contract/locales.json');
  assert.deepEqual(
    contract.locales.map((locale) => locale.id),
    ['zh-CN', 'en-US', 'zh-TW'],
  );

  for (const relativePath of expectedGeneratedFiles) {
    const absolutePath = path.join(root, relativePath);
    assert.ok(fs.existsSync(absolutePath), `missing generated contract file: ${relativePath}`);
    assert.match(fs.readFileSync(absolutePath, 'utf8'), /generated by scripts\/generate-i18n-contract\.mjs/);
  }
  for (const relativePath of expectedGeneratedJsonFiles) {
    const absolutePath = path.join(root, relativePath);
    assert.ok(fs.existsSync(absolutePath), `missing generated contract JSON file: ${relativePath}`);
    JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
  }

  execFileSync(process.execPath, ['scripts/generate-i18n-contract.mjs', '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});

test('shared i18n terms exist for every canonical locale with matching keys', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const expectedLocaleIds = contract.locales.map((locale) => locale.id);

  assert.ok(fs.existsSync(sharedTermsDir), 'missing shared i18n terms directory');

  const baseline = readJson(`src/shared/i18n/resources/shared/${expectedLocaleIds[0]}/terms.json`);
  const baselineKeys = flattenKeys(baseline);

  for (const localeId of expectedLocaleIds) {
    const relativePath = `src/shared/i18n/resources/shared/${localeId}/terms.json`;
    const terms = readJson(relativePath);
    assert.deepEqual(flattenKeys(terms), baselineKeys, `${relativePath} key set differs from baseline`);
  }
});

test('core runtime uses the generated locale contract for language identity', () => {
  const typesSource = readText('src/crates/assembly/core/src/service/i18n/types.rs');
  assert.match(
    typesSource,
    /generated_locale_contract::\{[\s\S]*GENERATED_LOCALE_CONTRACT/,
    'LocaleId and LocaleMetadata should derive identity fields from the generated contract',
  );
  assert.doesNotMatch(
    typesSource,
    /locale_registry::\{[\s\S]*(LOCALE_REGISTRY|locale_entry|locale_entry_from_code)/,
    'types.rs must not read language identity from the backend resource registry',
  );

  const resourceRegistrySource = readText('src/crates/assembly/core/src/service/i18n/locale_registry.rs');
  assert.doesNotMatch(
    resourceRegistrySource,
    /\b(name|english_name|native_name|rtl|model_language_name|short_model_instruction|aliases):/,
    'backend locale_registry.rs should only own Fluent resource wiring, not duplicate locale identity',
  );
});

test('shared i18n terms are consumed by each product surface runtime', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /SHARED_TERMS_BY_LOCALE/, 'Web UI should merge shared terms into i18next resources');

  const mobileMessagesSource = readText('src/mobile-web/src/i18n/messages.ts');
  assert.match(mobileMessagesSource, /SHARED_TERMS_BY_LOCALE/, 'mobile-web should expose shared terms through its message tree');

  const installerLanguagesSource = readText('BitFun-Installer/src/i18n/languages.ts');
  assert.match(installerLanguagesSource, /SHARED_TERMS_BY_APP_LANGUAGE/, 'installer should merge shared terms into its i18next resources');

  const coreServiceSource = readText('src/crates/assembly/core/src/service/i18n/service.rs');
  assert.match(coreServiceSource, /generated_shared_term/, 'core i18n service should resolve generated shared terms');
});

test('frontend runtimes use generated locale defaults and fallback chains', () => {
  const webPresetIndexSource = readText('src/web-ui/src/infrastructure/i18n/presets/index.ts');
  assert.doesNotMatch(
    webPresetIndexSource,
    /export const DEFAULT_(?:FALLBACK_)?LOCALE\s*=\s*['"]/,
    'Web UI preset defaults should be re-exported from the generated contract, not hard-coded',
  );

  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /getLocaleFallbackChain/, 'Web UI i18next should use the generated locale fallback chain');

  const mobileProviderSource = readText('src/mobile-web/src/i18n/I18nProvider.tsx');
  assert.match(mobileProviderSource, /getMobileFallbackChain/, 'mobile-web translate should use the generated locale fallback chain');
  assert.doesNotMatch(
    mobileProviderSource,
    /messages\[DEFAULT_LANGUAGE\]/,
    'mobile-web translate should not fall back directly to the surface default only',
  );

  const installerI18nSource = readText('BitFun-Installer/src/i18n/index.ts');
  assert.match(installerI18nSource, /DEFAULT_INSTALLER_UI_LANGUAGE/, 'installer i18next should use the generated default UI language');
  assert.match(installerI18nSource, /getInstallerUiFallbackChain/, 'installer i18next should use the generated locale fallback chain');
});

test('web-ui runtime keeps locale namespaces lazy outside its bootstrap set', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');

  assert.match(webI18nSource, /WEB_UI_BOOTSTRAP_NAMESPACES/, 'Web UI should declare the small eager namespace set');
  assert.match(webI18nSource, /import\.meta\.glob\('\.\.\/\.\.\/\.\.\/locales\/\*\*\/\*\.json'/, 'Web UI should keep a lazy namespace glob for non-bootstrap resources');
  const lazyGlobBlock = webI18nSource.match(/const lazyLocaleModules = import\.meta\.glob\([\s\S]*?\) as/)?.[0] ?? '';
  assert.doesNotMatch(
    lazyGlobBlock,
    /eager:\s*true/,
    'Web UI must not eagerly import every locale namespace',
  );
});

test('web-ui synchronous i18nService.t namespaces stay in the bootstrap set', () => {
  const registrySource = readText('src/web-ui/src/infrastructure/i18n/presets/namespaceRegistry.ts');
  const bootstrapNamespaces = new Set(extractStringArrayConstant(registrySource, 'WEB_UI_BOOTSTRAP_NAMESPACES'));
  const sourceRoot = path.join(root, 'src', 'web-ui', 'src');
  const missing = new Set();

  const sourceFiles = listFiles(sourceRoot, (file) => {
    const normalized = file.replace(/\\/g, '/');
    return (
      /\.(ts|tsx)$/.test(file) &&
      !normalized.includes('/locales/') &&
      !normalized.endsWith('.test.ts') &&
      !normalized.endsWith('.test.tsx') &&
      !normalized.endsWith('.spec.ts') &&
      !normalized.endsWith('.spec.tsx')
    );
  });

  for (const file of sourceFiles) {
    const text = fs.readFileSync(file, 'utf8');
    const patterns = [/i18nService\.t\(\s*(['"`])([^'"`:]+):/g];
    if (text.includes('i18nService.getT()')) {
      patterns.push(/\bt\(\s*(['"`])([^'"`:]+):/g);
    }

    for (const pattern of patterns) {
      for (const match of text.matchAll(pattern)) {
        const namespace = match[2];
        if (!bootstrapNamespaces.has(namespace)) {
          missing.add(`${namespace} (${path.relative(root, file).replace(/\\/g, '/')})`);
        }
      }
    }
  }

  assert.deepEqual(
    [...missing].sort(),
    [],
    'synchronous i18nService.t(...) call sites require eager bootstrap namespaces',
  );
});

test('web-ui slash command picker distinguishes all commands from quick actions', () => {
  const source = readText('src/web-ui/src/flow_chat/components/ChatInput.tsx');
  const allCommandsStart = source.indexOf("if (slashCommandState.kind === 'all')");
  const allCommandsEnd = source.indexOf('if (!canSwitchModes)', allCommandsStart);
  assert.notEqual(allCommandsStart, -1, 'ChatInput should render an all-command slash picker state');
  assert.notEqual(allCommandsEnd, -1, 'ChatInput all-command branch should stay before the mode-only branch');

  const allCommandsBlock = source.slice(allCommandsStart, allCommandsEnd);
  assert.match(
    allCommandsBlock,
    /t\('chatInput\.commands'\)/,
    'all-command slash picker should use a Commands label, not the quick-action label',
  );
  assert.doesNotMatch(
    allCommandsBlock,
    /t\('chatInput\.quickAction'\)/,
    'all-command slash picker must not reuse the quick-action label',
  );

  const contract = readJson('src/shared/i18n/contract/locales.json');
  for (const locale of contract.locales.map((entry) => entry.id)) {
    const resource = readJson(`src/web-ui/src/locales/${locale}/flow-chat.json`);
    const commands = getValueByPath(resource, 'chatInput.commands');
    const quickAction = getValueByPath(resource, 'chatInput.quickAction');
    assert.equal(typeof commands, 'string', `${locale} flow-chat chatInput.commands should exist`);
    assert.notEqual(commands, quickAction, `${locale} chatInput.commands should not duplicate chatInput.quickAction`);
  }
});

test('review platform relative time labels are locale resources', () => {
  const source = readText('src/web-ui/src/app/components/panels/review-platform/ReviewPlatformPanel.tsx');

  assert.match(source, /common:reviewPlatform\.relativeTime\.minutesAgo/, 'minute relative time label should be localized');
  assert.match(source, /common:reviewPlatform\.relativeTime\.hoursAgo/, 'hour relative time label should be localized');
  assert.match(source, /common:reviewPlatform\.relativeTime\.daysAgo/, 'day relative time label should be localized');
  assert.doesNotMatch(source, /`[^`]*\bm ago`/, 'relative minute text must not be hard-coded in ReviewPlatformPanel');
  assert.doesNotMatch(source, /`[^`]*\bh ago`/, 'relative hour text must not be hard-coded in ReviewPlatformPanel');
  assert.doesNotMatch(source, /`[^`]*\bd ago`/, 'relative day text must not be hard-coded in ReviewPlatformPanel');

  const contract = readJson('src/shared/i18n/contract/locales.json');
  for (const locale of contract.locales.map((entry) => entry.id)) {
    const resource = readJson(`src/web-ui/src/locales/${locale}/common.json`);
    for (const key of [
      'reviewPlatform.relativeTime.minutesAgo',
      'reviewPlatform.relativeTime.hoursAgo',
      'reviewPlatform.relativeTime.daysAgo',
    ]) {
      const value = getValueByPath(resource, key);
      assert.equal(typeof value, 'string', `${locale} common ${key} should exist`);
      assert.match(value, /\{\{\s*count\s*\}\}/, `${locale} common ${key} should interpolate count`);
    }
  }
});

test('i18n audit enforces the checked-in hardcoded source candidate budget', () => {
  const baselineSource = readText('scripts/i18n-hardcoded-baseline.json');
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.doesNotThrow(() => JSON.parse(baselineSource));
  assert.match(auditSource, /i18n-hardcoded-baseline\.json/, 'i18n:audit should read the hardcoded copy baseline');
  assert.match(auditSource, /auditHardcodedSourceBudgets/, 'i18n:audit should fail when hardcoded candidate budgets grow');
});

test('i18n audit treats locale key parity as an error', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const parityFunction = auditSource.match(/function auditKeyParity\(namespaces\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json is missing/, 'missing locale keys should fail i18n:audit');
  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json has/, 'extra locale keys should fail i18n:audit');
  assert.match(auditSource, /auditMobileWebMessageParity/, 'mobile-web message keys should be covered by i18n:audit');
  assert.match(auditSource, /auditInstallerKeyParity/, 'installer locale keys should be covered by i18n:audit');
});

test('CI runs i18n contract and audit guards before frontend builds', () => {
  const ciSource = readText('.github/workflows/ci.yml');
  const contractIndex = ciSource.indexOf('pnpm run i18n:contract:test:ci');
  const auditIndex = ciSource.indexOf('pnpm run i18n:audit');
  const buildIndex = ciSource.indexOf('pnpm run build:web');

  assert.notEqual(contractIndex, -1, 'CI should run pnpm run i18n:contract:test:ci');
  assert.notEqual(auditIndex, -1, 'CI should run pnpm run i18n:audit');
  assert.ok(contractIndex < buildIndex, 'i18n contract checks should run before web build');
  assert.ok(contractIndex < auditIndex, 'CI should run the fast contract check before the full i18n audit');
  assert.ok(auditIndex < buildIndex, 'i18n audit should run before web build');
});

test('i18n audit enforces interpolation parameter parity across resource formats', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /auditWebI18nextPlaceholderParity/, 'Web UI JSON placeholders should be audited');
  assert.match(auditSource, /auditMobileWebPlaceholderParity/, 'mobile-web placeholders should be audited');
  assert.match(auditSource, /auditInstallerPlaceholderParity/, 'installer placeholders should be audited');
  assert.match(auditSource, /auditCoreFluentParity/, 'core Fluent keys and placeholders should be audited');
  assert.match(auditSource, /auditRelayStaticHomepageResources/, 'relay static homepage resources should be audited');
  assert.match(auditSource, /extractI18nextPlaceholders/, 'i18next placeholder extraction should be explicit');
  assert.match(auditSource, /extractMobilePlaceholders/, 'mobile placeholder extraction should be explicit');
  assert.match(auditSource, /extractFluentPlaceholders/, 'Fluent placeholder extraction should be explicit');
});

test('i18n audit report surface summaries derive from owned scan and budget sources', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.doesNotMatch(
    auditSource,
    /const governanceSurfaceIds\s*=\s*\[/,
    'governance report surface summaries should derive from the governance baseline dimensions',
  );
  assert.doesNotMatch(
    auditSource,
    /const localeFormatSurfaceIds\s*=\s*\[/,
    'locale format report surface summaries should derive from the locale-format scan specs',
  );
  assert.match(
    auditSource,
    /collectGovernanceBudgetSurfaceIds/,
    'governance report should collect zero-count surfaces from the baseline bySurface budgets',
  );
  assert.match(
    auditSource,
    /createLocaleFormatScanSpecs/,
    'locale format report should reuse the same scan specs for scanning and zero-count summaries',
  );
});

test('i18n audit fails literal fallbacks and unknown static keys', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const sourceTextAudit = auditSource.match(/function auditSourceText\(\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(sourceTextAudit, /reportError/, 'literal t(key, "fallback") candidates should fail audit');
  assert.match(auditSource, /auditWebUiStaticTranslationKeys/, 'static Web UI translation keys should be checked');
  assert.match(auditSource, /collectWebUiStaticTranslationKeys/, 'static key collection should be explicit');
});

test('i18n audit gates object-form literal fallbacks with an explicit budget', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const fallbackBaselineSource = readText('scripts/i18n-literal-fallback-baseline.json');
  const fallbackBaseline = JSON.parse(fallbackBaselineSource);

  assert.ok(
    fallbackBaseline.budgets.every((entry) => (
      entry.literalDefaultValues &&
      typeof entry.literalDefaultValues === 'object' &&
      !Array.isArray(entry.literalDefaultValues)
    )),
    'literal fallback baseline should allowlist exact keys per file',
  );
  assert.match(auditSource, /i18n-literal-fallback-baseline\.json/, 'audit should read the literal fallback baseline');
  assert.match(auditSource, /auditWebUiLiteralFallbackBudget/, 'object-form defaultValue fallbacks should have a no-growth gate');
  assert.match(auditSource, /defaultValue/, 'audit should inspect i18next defaultValue options');
});

auditIntegrationTest('i18n audit reports literal fallback and locale formatting candidate baselines', { concurrency: false }, () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const localeFormatBaselineSource = readText('scripts/i18n-locale-format-baseline.json');
  const localeFormatBaseline = JSON.parse(localeFormatBaselineSource);

  assert.match(auditSource, /literalDefaultValueFallbacks/, 'governance report should include literal fallback candidates');
  assert.match(auditSource, /i18n-locale-format-baseline\.json/, 'audit should read the direct locale format baseline');
  assert.match(auditSource, /auditLocaleFormatUsageBudget/, 'direct locale formatting should have a no-growth gate');
  assert.ok(
    localeFormatBaseline.budgets.every((entry) => (
      typeof entry.path === 'string' &&
      typeof entry.maxLocaleFormatCalls === 'number'
    )),
    'locale format baseline should use exact per-file budgets',
  );

  const reportPath = 'scripts/.tmp-i18n-locale-format-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    const result = runI18nAudit(['--report-json', reportPath]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    const report = readJson(reportPath);
    assert.equal(
      report.summary.byCategory.localeFormatCandidates.bySurface['web-ui'],
      report.localeFormatCandidates.filter((entry) => entry.surface === 'web-ui').length,
      'report should summarize direct locale formatting candidates by surface',
    );
    assert.ok(
      report.summary.byCategory.literalDefaultValueFallbacks.byFile,
      'report should summarize literal fallbacks by file',
    );
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }

  const baselinePath = 'scripts/i18n-locale-format-baseline.json';
  const baseline = readJson(baselinePath);
  baseline.budgets.push({
    path: 'src/web-ui/src/__removed_locale_format_fixture__.ts',
    maxLocaleFormatCalls: 1,
  });

  withTemporaryTextFile(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale direct locale format baselines must fail audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /no longer has direct locale formatting call/,
      'audit output should explain the stale locale format budget',
    );
  });

  withTemporaryTextFile('src/web-ui/src/__locale_format_fixture__.ts', 'export const value = Intl.NumberFormat().format(1234);\n', () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'direct Intl format calls without new must fail audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /__locale_format_fixture__\.ts has 1 direct locale formatting call/,
      'audit output should report direct Intl format calls without new',
    );
  });
});

test('i18n audit can emit a machine-readable governance report', { concurrency: false }, () => {
  const reportPath = 'scripts/.tmp-i18n-governance-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    const result = runI18nAudit(['--report-json', reportPath]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    assert.ok(fs.existsSync(absoluteReportPath), 'audit should write the requested report file');

    const report = readJson(reportPath);
    assert.equal(report.version, 1);
    assert.equal(report.generatedBy, 'scripts/i18n-audit.mjs');
    assert.ok(Array.isArray(report.confirmedUnusedKeys), 'report should include confirmed unused keys');
    assert.ok(Array.isArray(report.dynamicKeyCandidates), 'report should include dynamic key candidates');
    assert.ok(Array.isArray(report.sharedTermDuplicates), 'report should include shared-term duplicate candidates');
    assert.ok(Array.isArray(report.sameTextLocaleInventory), 'report should include same-text locale inventory');
    assert.ok(Array.isArray(report.l10nQualityCandidates), 'report should include l10n quality candidates');
    assert.ok(Array.isArray(report.literalDefaultValueFallbacks), 'report should include literal defaultValue fallback candidates');
    assert.ok(Array.isArray(report.localeFormatCandidates), 'report should include direct locale formatting candidates');
    assert.deepEqual(
      report.summary.counts,
      {
        confirmedUnusedKeys: report.confirmedUnusedKeys.length,
        dynamicKeyCandidates: report.dynamicKeyCandidates.length,
        sharedTermDuplicates: report.sharedTermDuplicates.length,
        sameTextLocaleInventory: report.sameTextLocaleInventory.length,
        l10nQualityCandidates: report.l10nQualityCandidates.length,
        literalDefaultValueFallbacks: report.literalDefaultValueFallbacks.length,
        localeFormatCandidates: report.localeFormatCandidates.length,
      },
      'report counts should match finding arrays',
    );
    assert.equal(report.summary.baseline.path, 'scripts/i18n-governance-baseline.json');
    assert.equal(report.summary.baseline.enforced, true);
    const sharedDuplicateSample = report.sharedTermDuplicates[0];
    if (sharedDuplicateSample) {
      assert.equal(
        report.summary.byCategory.sharedTermDuplicates.bySharedKey[sharedDuplicateSample.sharedKey],
        report.sharedTermDuplicates.filter((entry) => entry.sharedKey === sharedDuplicateSample.sharedKey).length,
        'report should summarize shared-term duplicates by shared term',
      );
    }
    assert.equal(
      report.summary.byCategory.l10nQualityCandidates.bySurface['web-ui'] ?? 0,
      report.l10nQualityCandidates.filter((entry) => entry.surface === 'web-ui').length,
      'report should summarize l10n candidates by surface',
    );
    assert.equal(
      report.summary.byCategory.sameTextLocaleInventory.bySurface['web-ui'] ?? 0,
      report.sameTextLocaleInventory.filter((entry) => entry.surface === 'web-ui').length,
      'report should summarize same-text locale inventory by surface',
    );
    assert.ok(
      report.sameTextLocaleInventory.length > report.l10nQualityCandidates.length,
      'same-text locale inventory should retain broad non-blocking review data beyond actionable l10n signals',
    );
    assert.equal(
      report.summary.byCategory.l10nQualityCandidates.byNamespace['flow-chat'] ?? 0,
      report.l10nQualityCandidates.filter((entry) => entry.namespace === 'flow-chat').length,
      'report should summarize l10n candidates by namespace',
    );
    assert.equal(
      report.summary.byCategory.dynamicKeyCandidates.byProofState['source-proven'],
      report.dynamicKeyCandidates.length,
      'report should summarize source-proven dynamic key contracts separately from unproved candidates',
    );
    assert.ok(
      report.dynamicKeyCandidates.every((entry) => entry.proofState === 'source-proven'),
      'dynamic key contracts should include their proof state for review and metrics',
    );
    assert.ok(
      report.dynamicKeyCandidates.some((entry) => (
        entry.allowlistId === 'installer-install-path-errors' &&
        entry.surface === 'installer' &&
        entry.key === 'errors.installPath.notAbsolute'
      )),
      'installer backend error-code mapping should be reported as a dynamic key contract',
    );
    assert.ok(
      report.sharedTermDuplicates.every((entry) => entry.resourceKey !== entry.sharedResourceKey),
      'shared-term duplicate findings should only report surface copies, not the shared source entry itself',
    );
    assert.equal(
      report.l10nQualityCandidates.length,
      0,
      'reviewed same-writing zh-CN/zh-TW copy without a script or terminology signal should not create l10n noise',
    );
    assert.ok(
      report.literalDefaultValueFallbacks.every((entry) => entry.file && entry.key && entry.location),
      'literal fallback candidates should include file, key, and location for cleanup reviews',
    );
    assert.ok(
      report.localeFormatCandidates.every((entry) => entry.surface && entry.file && entry.location),
      'locale format candidates should include surface, file, and location for cleanup reviews',
    );
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }
});

auditIntegrationTest('i18n audit reports same-text zh-TW copy with a l10n signal', { concurrency: false }, () => {
  const localePath = 'src/web-ui/src/locales/zh-TW/settings/acp-agents.json';
  const reportPath = 'scripts/.tmp-i18n-l10n-signal-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  const source = readText(localePath);
  const fixture = source.replace('"learnMore": "瞭解更多"', '"learnMore": "了解更多"');

  assert.notEqual(fixture, source, 'test fixture should introduce same-text zh-TW terminology debt');
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    withTemporaryTextFile(localePath, fixture, () => {
      const result = runI18nAudit(['--report-json', reportPath]);
      assert.notEqual(result.status, 0, 'same-text zh-TW terminology debt should exceed the zero l10n baseline');

      const report = readJson(reportPath);
      assert.ok(
        report.l10nQualityCandidates.some((entry) => (
          entry.surface === 'web-ui' &&
          entry.namespace === 'settings/acp-agents' &&
          entry.key === 'actions.learnMore' &&
          entry.locale === 'zh-TW' &&
          entry.comparisonLocale === 'zh-CN' &&
          entry.signal?.type === 'terminology' &&
          entry.signal?.match === '了解'
        )),
        'audit report should include the concrete same-text terminology signal',
      );
      assert.ok(
        report.sameTextLocaleInventory.some((entry) => (
          entry.surface === 'web-ui' &&
          entry.namespace === 'settings/acp-agents' &&
          entry.key === 'actions.learnMore' &&
          entry.locale === 'zh-TW' &&
          entry.comparisonLocale === 'zh-CN' &&
          entry.signalType === 'terminology' &&
          entry.allowlistState === 'unreviewed'
        )),
        'audit inventory should retain the same-text pair even though only signal-bearing entries are governance candidates',
      );
    });
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }
});

auditIntegrationTest('mobile-web uses shared terms for stable shared concept labels', { concurrency: false }, () => {
  const reportPath = 'scripts/.tmp-i18n-mobile-shared-terms-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    const result = runI18nAudit(['--report-json', reportPath]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);

    const report = readJson(reportPath);
    const migratedSharedKeys = new Set([
      'product.remote',
      'features.workspace',
      'modes.assistant',
      'modes.expert',
      'agents.claw',
      'agents.code',
      'agents.cowork',
      'agents.default',
      'tools.edit',
      'tools.explore',
      'tools.read',
      'tools.shell',
      'tools.todo',
      'tools.write',
    ]);
    const mobileDuplicates = report.sharedTermDuplicates
      .filter((entry) => entry.surface === 'mobile-web' && migratedSharedKeys.has(entry.sharedKey))
      .map((entry) => `${entry.sharedKey}:${entry.key}:${entry.locale}`)
      .sort();
    const legacyMobileKeys = [
      'common.appName',
      'sessions.workspace',
      'sessions.assistantMode',
      'sessions.coworkSession',
      'sessions.codeSession',
      'sessions.defaultAssistant',
      'sessions.agentClaw',
      'sessions.proMode',
      'workspace.title',
      'tools.edit',
      'tools.explore',
      'tools.read',
      'tools.shell',
      'tools.todo',
      'tools.write',
    ];
    const mobileSourceFiles = listFiles(path.join(root, 'src', 'mobile-web', 'src'), (file) => (
      /\.(?:ts|tsx)$/.test(file) && !file.endsWith(`${path.sep}i18n${path.sep}messages.ts`)
    ));
    const legacyReferences = mobileSourceFiles.flatMap((file) => {
      const source = fs.readFileSync(file, 'utf8');
      return legacyMobileKeys
        .filter((key) => source.includes(`'${key}'`) || source.includes(`"${key}"`))
        .map((key) => `${path.relative(root, file)}:${key}`);
    }).sort();

    assert.deepEqual(
      mobileDuplicates,
      [],
      'mobile-web should read migrated stable labels from shared terms instead of copying values',
    );
    assert.deepEqual(
      legacyReferences,
      [],
      'mobile-web source should not call removed local keys for migrated shared terms',
    );
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }
});

auditIntegrationTest('web-ui uses shared terms for stable navigation and feature labels', { concurrency: false }, () => {
  const reportPath = 'scripts/.tmp-i18n-web-ui-shared-terms-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    const result = runI18nAudit(['--report-json', reportPath]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);

    const report = readJson(reportPath);
    const migratedResourceKeys = new Set([
      'common:app.name',
      'common:header.remoteConnect',
      'common:nav.sections.workspace',
      'common:nav.sessions.newCodeSessionShort',
      'common:nav.sessions.newCoworkSessionShort',
      'common:scenes.settings',
      'common:tabs.settings',
      'common:remoteConnect.title',
      'common:remoteConnect.tabBitfunServer',
      'common:remoteConnect.tabLan',
      'flow-chat:layout.noPanels',
      'flow-chat:deepReviewActionBar.minimizedDeep',
      'flow-chat:toolCards.codeReview.reviewMode',
      'flow-chat:toolbar.settings',
      'flow-chat:toolCards.sessionControl.workspace',
      'flow-chat:toolCards.sessionMessage.workspace',
      'flow-chat:welcome.workspace',
      'scenes/skills:suite.modes.claw',
      'settings:title',
      'settings:configCenter.title',
      'settings/review:overview.badge',
      'settings:workspace.title',
      'settings/lsp:tabs.settings',
    ]);
    const webUiDuplicates = report.sharedTermDuplicates
      .filter((entry) => entry.surface === 'web-ui' && migratedResourceKeys.has(entry.resourceKey))
      .map((entry) => `${entry.sharedKey}:${entry.resourceKey}:${entry.locale}`)
      .sort();
    const legacyWebUiKeys = [
      'header.remoteConnect',
      'remoteConnect.title',
      'remoteConnect.tabBitfunServer',
      'remoteConnect.tabLan',
      'nav.sections.workspace',
      'nav.sessions.newCodeSessionShort',
      'nav.sessions.newCoworkSessionShort',
      'scenes.settings',
      'tabs.settings',
      'layout.noPanels',
      'deepReviewActionBar.minimizedDeep',
      'toolbar.settings',
      'toolCards.codeReview.reviewMode',
      'toolCards.sessionControl.workspace',
      'toolCards.sessionMessage.workspace',
      'welcome.workspace',
      'suite.modes.claw',
      'configCenter.title',
      'overview.badge',
      'workspace.title',
    ];
    const webUiSourceFiles = listFiles(path.join(root, 'src', 'web-ui', 'src'), (file) => (
      /\.(?:ts|tsx)$/.test(file)
    ));
    const legacyReferences = webUiSourceFiles.flatMap((file) => {
      const source = fs.readFileSync(file, 'utf8');
      return legacyWebUiKeys
        .filter((key) => source.includes(`'${key}'`) || source.includes(`"${key}"`))
        .map((key) => `${path.relative(root, file)}:${key}`);
    }).sort();

    assert.deepEqual(
      webUiDuplicates,
      [],
      'web-ui should resolve migrated stable labels from shared terms instead of copied values',
    );
    assert.deepEqual(
      legacyReferences,
      [],
      'web-ui source should not call removed local keys for migrated shared terms',
    );
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }
});

test('installer uses the shared product name for titlebar defaults', { concurrency: false }, () => {
  const appSource = readText('BitFun-Installer/src/App.tsx');
  const localePaths = [
    'BitFun-Installer/src/i18n/locales/en.json',
    'BitFun-Installer/src/i18n/locales/zh.json',
    'BitFun-Installer/src/i18n/locales/zh-TW.json',
  ];

  assert.match(
    appSource,
    /shared\.product\.name/,
    'installer titlebar default should read the canonical shared product name',
  );
  assert.doesNotMatch(
    appSource,
    /titlebar\.default/,
    'installer source should not call the removed copied titlebar.default key',
  );

  for (const localePath of localePaths) {
    const resource = readJson(localePath);
    assert.equal(
      resource.titlebar,
      undefined,
      `${localePath} should not duplicate the shared product name under titlebar.default`,
    );
  }
});

auditIntegrationTest('core and relay static homepage reuse shared product and feature terms', { concurrency: false }, () => {
  const reportPath = 'scripts/.tmp-i18n-core-relay-shared-terms-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  fs.rmSync(absoluteReportPath, { force: true });

  try {
    const result = runI18nAudit(['--report-json', reportPath]);
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);

    const report = readJson(reportPath);
    const blockedDuplicates = report.sharedTermDuplicates
      .filter((entry) => (
        (entry.surface === 'core' && entry.sharedKey === 'product.name') ||
        (entry.surface === 'relay-static-homepage' && entry.sharedKey === 'features.remoteControl')
      ))
      .map((entry) => `${entry.surface}:${entry.sharedKey}:${entry.resourceKey}:${entry.locale}`)
      .sort();
    assert.deepEqual(
      blockedDuplicates,
      [],
      'core product name and relay remote-control label should be resolved from shared terms instead of copied values',
    );

    for (const locale of ['en-US', 'zh-CN', 'zh-TW']) {
      const fluentSource = readText(`src/crates/assembly/core/locales/${locale}.ftl`);
      assert.doesNotMatch(fluentSource, /^app-name\s*=/m, `${locale}.ftl should not copy shared.product.name`);
    }

    const coreServiceSource = readText('src/crates/assembly/core/src/service/i18n/service.rs');
    assert.match(
      coreServiceSource,
      /legacy_shared_term_key/,
      'core i18n service should keep a compatibility alias for legacy app-name callers',
    );

    const relayMessages = readJson('src/apps/relay-server/static/homepage/i18n.json');
    assert.deepEqual(
      relayMessages['en-US'].flowMobileSub,
      { $shared: 'features.remoteControl' },
      'relay homepage should reference the shared remote-control term instead of copying it',
    );
    const relayShared = readJson('src/apps/relay-server/static/homepage/i18n.shared.json');
    const sharedTerms = readJson('src/shared/i18n/resources/shared/zh-TW/terms.json');
    assert.equal(relayShared['zh-TW'].features.remoteControl, sharedTerms.features.remoteControl);

    const relayHtml = readText('src/apps/relay-server/static/homepage/index.html');
    assert.match(relayHtml, /i18n\.shared\.json/, 'relay homepage should load its small generated shared-term resource');
    assert.match(relayHtml, /\$shared/, 'relay homepage runtime should resolve shared-term references');
  } finally {
    fs.rmSync(absoluteReportPath, { force: true });
  }
});

auditIntegrationTest('i18n audit fails stale relay static shared-term references', { concurrency: false }, () => {
  const relayPath = 'src/apps/relay-server/static/homepage/i18n.json';
  const relayMessages = readJson(relayPath);
  relayMessages['en-US'].flowMobileSub = { $shared: 'features.__missingForTest' };

  withTemporaryTextFile(relayPath, `${JSON.stringify(relayMessages, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale relay $shared references must fail i18n:audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /relay static homepage en-US key "flowMobileSub" references missing shared term "features\.__missingForTest"/,
      'audit output should identify the stale relay shared-term reference',
    );
  });
});

auditIntegrationTest('i18n audit enforces governance candidate baselines', { concurrency: false }, () => {
  const baselinePath = 'scripts/i18n-governance-baseline.json';
  const baseline = readJson(baselinePath);

  baseline.budgets.sharedTermDuplicates.maxTotal = 0;

  withTemporaryTextFile(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'shared-term duplicate growth over baseline must fail ordinary i18n:audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /sharedTermDuplicates has \d+ candidate\(s\), baseline is 0/,
      'audit output should identify the governance baseline category that failed',
    );
  });
});

auditIntegrationTest('i18n audit enforces governance baseline dimensions', { concurrency: false }, () => {
  const baselinePath = 'scripts/i18n-governance-baseline.json';
  const baseline = readJson(baselinePath);
  const sharedKeyUnderTest = Object.entries(baseline.budgets.sharedTermDuplicates.bySharedKey)
    .find(([, count]) => count > 0)?.[0];
  assert.ok(sharedKeyUnderTest, 'baseline should contain at least one sharedKey dimension with current debt');

  baseline.budgets.sharedTermDuplicates.bySharedKey[sharedKeyUnderTest] = 0;

  withTemporaryTextFile(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'shared-term duplicate growth by sharedKey must fail ordinary i18n:audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      new RegExp(`sharedTermDuplicates sharedKey ${escapeRegExp(sharedKeyUnderTest)} has \\d+ candidate\\(s\\), baseline is 0`),
      'audit output should identify the sharedKey dimension that failed',
    );
  });
});

auditIntegrationTest('i18n audit fails stale l10n identical allowlist entries', { concurrency: false }, () => {
  const allowlistPath = 'scripts/i18n-l10n-identical-allowlist.json';
  const allowlist = readJson(allowlistPath);

  allowlist.entries.push({
    id: 'stale-test-l10n-identical-key',
    surface: 'shared',
    namespace: 'shared',
    locale: 'zh-TW',
    comparisonLocale: 'zh-CN',
    owner: 'scripts/i18n-contract.test.mjs',
    reason: 'Test fixture for stale l10n identical governance.',
    keys: ['__missingGovernanceKey__'],
  });

  withTemporaryTextFile(allowlistPath, `${JSON.stringify(allowlist, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale l10n identical allowlist keys must fail ordinary i18n:audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /stale-test-l10n-identical-key.*__missingGovernanceKey__/,
      'audit output should identify the stale l10n allowlist key',
    );
  });
});

auditIntegrationTest('i18n audit validates l10n identical allowlist array fields', { concurrency: false }, () => {
  const allowlistPath = 'scripts/i18n-l10n-identical-allowlist.json';
  const allowlist = readJson(allowlistPath);

  allowlist.entries.push({
    id: 'invalid-test-l10n-identical-key-array',
    surface: 'shared',
    namespace: 'shared',
    locale: 'zh-TW',
    comparisonLocale: 'zh-CN',
    owner: 'scripts/i18n-contract.test.mjs',
    reason: 'Test fixture for invalid l10n identical governance.',
    keys: 'shared:modes.',
  });

  withTemporaryTextFile(allowlistPath, `${JSON.stringify(allowlist, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'l10n identical allowlist keys must be an array');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /L10n identical allowlist "invalid-test-l10n-identical-key-array" keys must be an array/,
      'audit output should identify the invalid l10n allowlist field',
    );
  });
});

auditIntegrationTest('i18n audit fails stale dynamic key allowlist entries', { concurrency: false }, () => {
  const allowlistPath = 'scripts/i18n-dynamic-key-allowlist.json';
  const reportPath = 'scripts/.tmp-i18n-stale-dynamic-key-report.json';
  const absoluteReportPath = path.join(root, reportPath);
  const allowlist = readJson(allowlistPath);

  allowlist.entries.push({
    id: 'stale-test-dynamic-key',
    surface: 'installer',
    owner: 'scripts/i18n-contract.test.mjs',
    description: 'Test fixture for stale dynamic key governance.',
    keys: ['errors.installPath.__missingGovernanceKey__'],
  });

  fs.rmSync(absoluteReportPath, { force: true });
  withTemporaryTextFile(allowlistPath, `${JSON.stringify(allowlist, null, 2)}\n`, () => {
    try {
      const result = runI18nAudit(['--report-json', reportPath]);
      assert.notEqual(result.status, 0, 'stale allowlist keys must fail i18n audit');
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        /stale-test-dynamic-key.*errors\.installPath\.__missingGovernanceKey__/,
        'audit output should identify the stale allowlist key',
      );
    } finally {
      fs.rmSync(absoluteReportPath, { force: true });
    }
  });
});

auditIntegrationTest('i18n audit fails stale dynamic key source references', { concurrency: false }, () => {
  const allowlistPath = 'scripts/i18n-dynamic-key-allowlist.json';
  const allowlist = readJson(allowlistPath);

  assert.ok(
    allowlist.entries.every((entry) => Array.isArray(entry.sourceReferences) && entry.sourceReferences.length > 0),
    'dynamic key allowlist entries should include sourceReferences that prove the owning code path',
  );

  allowlist.entries[0].sourceReferences = ['__missing_i18n_dynamic_key_source_reference__'];

  withTemporaryTextFile(allowlistPath, `${JSON.stringify(allowlist, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale dynamic key source references must fail ordinary i18n:audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /source reference "__missing_i18n_dynamic_key_source_reference__"/,
      'audit output should identify the missing dynamic key source reference',
    );
  });
});

test('i18n audit validates static hook translation keys with namespace context', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /use(?:I18n|Translation)/, 'audit should inspect hook namespace declarations');
  assert.match(auditSource, /hookNamespaceByTranslator/, 'audit should remember namespace aliases returned by hooks');
  assert.match(auditSource, /relative static Web UI i18n key/, 'audit should report missing relative hook keys clearly');
});

auditIntegrationTest('i18n audit catches array-namespace keys and stale literal fallback budgets', { concurrency: false }, () => {
  const arrayNamespaceFixture = 'src/web-ui/src/__i18n_array_namespace_audit_fixture__.tsx';
  const missingFullKey = 'components:__arrayNamespaceAuditMissingKey__';
  const missingRelativeKey = 'components:__arrayNamespaceAuditMissingRelativeKey__';
  const missingUseTranslationKey = 'common:__arrayNamespaceUseTranslationMissingKey__';

  withTemporaryTextFile(
    arrayNamespaceFixture,
    [
      "import { useI18n, useTranslation } from '@/infrastructure/i18n';",
      'export function I18nArrayNamespaceAuditFixture() {',
      "  const { t } = useI18n(['components', 'common', 'errors']);",
      "  const [translate] = useTranslation(['common', 'errors']);",
      `  return <div>{t('${missingFullKey}')}{t('__arrayNamespaceAuditMissingRelativeKey__')}{translate('${missingUseTranslationKey}')}</div>;`,
      '}',
      '',
    ].join('\n'),
    () => {
      const result = runI18nAudit();
      assert.notEqual(result.status, 0, 'array namespace full keys must be included in unknown-key audit');
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingFullKey),
        'audit output should identify the missing array-namespace key',
      );
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingRelativeKey),
        'audit output should resolve relative array-namespace keys against the first namespace',
      );
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        new RegExp(missingUseTranslationKey),
        'audit output should cover useTranslation array namespace aliases',
      );
    },
  );

  const baselinePath = 'scripts/i18n-literal-fallback-baseline.json';
  const baseline = readJson(baselinePath);
  baseline.budgets.push({
    path: 'src/web-ui/src/__removed_literal_fallback_fixture__.tsx',
    literalDefaultValues: {
      'common:actions.close': 1,
    },
  });

  withTemporaryTextFile(baselinePath, `${JSON.stringify(baseline, null, 2)}\n`, () => {
    const result = runI18nAudit();
    assert.notEqual(result.status, 0, 'stale literal fallback baseline entries must fail audit');
    assert.match(
      `${result.stdout}\n${result.stderr}`,
      /no longer has literal i18next defaultValue fallback/,
      'audit output should explain the stale literal fallback budget',
    );
  });
});

auditIntegrationTest('i18n audit catches composed literal defaultValue fallbacks', { concurrency: false }, () => {
  const composedFallbackFixture = 'src/web-ui/src/__i18n_composed_default_value_fixture__.tsx';

  withTemporaryTextFile(
    composedFallbackFixture,
    [
      "import { useI18n } from '@/infrastructure/i18n';",
      'export function I18nComposedDefaultValueFixture() {',
      "  const { t } = useI18n('flow-chat');",
      "  return <div>{t('flowChatHeader.turnBadge', { current: 1, defaultValue: `Turn ${1}` + ' fallback' })}</div>;",
      '}',
      '',
    ].join('\n'),
    () => {
      const result = runI18nAudit();
      assert.notEqual(result.status, 0, 'composed static defaultValue fallback should fail audit');
      assert.match(
        `${result.stdout}\n${result.stderr}`,
        /literal i18next defaultValue fallback/,
        'audit output should identify composed defaultValue fallback debt',
      );
    },
  );
});

test('i18n generation checks are stable across line endings', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');

  assert.match(generatorSource, /normalizeGeneratedText/, 'generated contract check should normalize line endings');
  assert.match(generatorSource, /currentContentForCheck/, 'generated contract check should compare normalized current content');
});

test('i18n audit preflights TypeScript before TypeScript-backed checks', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /loadTypeScriptForAudit/, 'audit should load TypeScript through a single preflight helper');
  assert.match(auditSource, /Run pnpm install/, 'missing TypeScript should tell contributors how to fix the local setup');
});

test('installer Rust locale contract is generated from the installer surface order', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');
  const installerRustGenerator = generatorSource.match(/function generateInstallerRustLocaleContract\(contract\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(installerRustGenerator, /orderedLocales\(contract, 'installer'\)/);
  assert.doesNotMatch(installerRustGenerator, /orderedLocales\(contract, 'core'\)/);
});

test('i18n contract surface resource roots point at existing owned resources', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const localeById = new Map(contract.locales.map((locale) => [locale.id, locale]));

  for (const [surface, config] of Object.entries(contract.surfaces)) {
    const resourceRoot = path.join(root, config.resourceRoot);
    assert.ok(fs.existsSync(resourceRoot), `${surface} resourceRoot does not exist: ${config.resourceRoot}`);

    for (const localeId of contract.surfaceOrders[surface] ?? []) {
      if (surface === 'web-ui') {
        assert.ok(fs.existsSync(path.join(resourceRoot, localeId)), `${surface} is missing ${localeId} locale directory`);
      } else if (surface === 'installer') {
        const locale = localeById.get(localeId);
        assert.ok(locale?.installer?.uiCode, `${localeId} is missing installer.uiCode`);
        assert.ok(fs.existsSync(path.join(resourceRoot, `${locale.installer.uiCode}.json`)), `${surface} is missing ${localeId} resource JSON`);
      } else if (surface === 'core') {
        assert.ok(fs.existsSync(path.join(resourceRoot, `${localeId}.ftl`)), `${surface} is missing ${localeId} Fluent resource`);
      } else if (surface === 'mobile-web') {
        assert.ok(fs.existsSync(path.join(resourceRoot, 'messages.ts')), `${surface} is missing messages.ts`);
      }
    }
  }
});
