import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const contractPath = path.join(root, 'src', 'shared', 'i18n', 'contract', 'locales.json');
const sharedTermsDir = path.join(root, 'src', 'shared', 'i18n', 'resources', 'shared');
const expectedGeneratedFiles = [
  'src/web-ui/src/infrastructure/i18n/presets/generatedLocaleContract.ts',
  'src/mobile-web/src/i18n/generatedLocaleContract.ts',
  'BitFun-Installer/src/i18n/generatedLocaleContract.ts',
  'src/crates/core/src/service/i18n/generated_locale_contract.rs',
  'BitFun-Installer/src-tauri/src/installer/generated_locale_contract.rs',
];

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8'));
}

function flattenKeys(value, prefix = '') {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    return prefix ? [prefix] : [];
  }

  return Object.entries(value)
    .flatMap(([key, child]) => flattenKeys(child, prefix ? `${prefix}.${key}` : key))
    .sort();
}

test('i18n contract generated files are in sync with the canonical contract', () => {
  assert.ok(fs.existsSync(contractPath), 'missing shared i18n locale contract');

  const contract = readJson('src/shared/i18n/contract/locales.json');
  assert.deepEqual(
    contract.locales.map((locale) => locale.id),
    ['zh-CN', 'en-US', 'zh-TW'],
  );

  for (const relativePath of expectedGeneratedFiles) {
    const absolutePath = path.join(root, relativePath);
    assert.ok(fs.existsSync(absolutePath), `missing generated contract file: ${relativePath}`);
    assert.match(fs.readFileSync(absolutePath, 'utf8'), /generated by scripts\/generate-i18n-contract\.mjs/);
  }

  execFileSync(process.execPath, ['scripts/generate-i18n-contract.mjs', '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});

test('shared i18n terms exist for every canonical locale with matching keys', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const expectedLocaleIds = contract.locales.map((locale) => locale.id);

  assert.ok(fs.existsSync(sharedTermsDir), 'missing shared i18n terms directory');

  const baseline = readJson(`src/shared/i18n/resources/shared/${expectedLocaleIds[0]}/terms.json`);
  const baselineKeys = flattenKeys(baseline);

  for (const localeId of expectedLocaleIds) {
    const relativePath = `src/shared/i18n/resources/shared/${localeId}/terms.json`;
    const terms = readJson(relativePath);
    assert.deepEqual(flattenKeys(terms), baselineKeys, `${relativePath} key set differs from baseline`);
  }
});
