// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit src/shared/i18n/contract/locales.json instead.
#[derive(Debug, Clone, Copy)]
pub struct InstallerGeneratedLocaleEntry {
    pub code: &'static str,
    pub aliases: &'static [&'static str],
}

pub const INSTALLER_GENERATED_LOCALES: &[InstallerGeneratedLocaleEntry] = &[
    InstallerGeneratedLocaleEntry {
        code: "zh-CN",
        aliases: &["zh", "zh-Hans", "zh-CN"],
    },
    InstallerGeneratedLocaleEntry {
        code: "zh-TW",
        aliases: &["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
    },
    InstallerGeneratedLocaleEntry {
        code: "en-US",
        aliases: &["en", "en-US"],
    }
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_installer_contract_keeps_canonical_aliases() {
        assert!(INSTALLER_GENERATED_LOCALES.iter().any(|locale| locale.code == "zh-CN" && locale.aliases.contains(&"zh")));
        assert!(INSTALLER_GENERATED_LOCALES.iter().any(|locale| locale.code == "zh-TW" && locale.aliases.contains(&"zh-Hant")));
        assert!(INSTALLER_GENERATED_LOCALES.iter().any(|locale| locale.code == "en-US" && locale.aliases.contains(&"en")));
    }
}
