// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit the shared i18n contract or shared terms instead.
export const MOBILE_LOCALES = [
  {
    id: "zh-CN",
    shortName: "中",
    aliases: ["zh", "zh-Hans", "zh-CN"],
    contentFallbacks: ["en-US"],
  },
  {
    id: "zh-TW",
    shortName: "繁",
    aliases: ["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
    contentFallbacks: ["zh-CN", "en-US"],
  },
  {
    id: "en-US",
    shortName: "EN",
    aliases: ["en", "en-US"],
    contentFallbacks: ["zh-CN"],
  }
] as const;
const UNKNOWN_LANGUAGE_FALLBACK_CHAIN = ["en-US", "zh-CN"] as const satisfies readonly MobileLanguage[];

const mobileLocaleAliasesByPriority = MOBILE_LOCALES
  .flatMap(locale => locale.aliases.map(alias => ({ locale, alias: alias.toLowerCase() })))
  .sort((a, b) => b.alias.length - a.alias.length);

export type MobileLanguage = (typeof MOBILE_LOCALES)[number]['id'];

export const DEFAULT_LANGUAGE = "en-US" satisfies MobileLanguage;

export type SharedI18nTerms = {
  readonly [key: string]: string | SharedI18nTerms;
};

export const SHARED_TERMS_BY_LOCALE = {
  "zh-CN": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "远程控制",
      "codeAgent": "代码助手",
      "deepReview": "严格审查",
      "settings": "设置",
      "workspace": "工作区",
      "accountLogin": "账户登录"
    },
    "modes": {
      "agentic": "代理模式",
      "assistant": "助手模式",
      "expert": "专家模式",
      "review": "评审模式"
    },
    "agents": {
      "code": "代码会话",
      "cowork": "协作会话",
      "claw": "Claw",
      "default": "默认助手"
    },
    "tools": {
      "explore": "探索",
      "read": "读取",
      "write": "写入",
      "shell": "命令行",
      "search": "搜索",
      "edit": "编辑",
      "todo": "待办"
    },
    "connectionMethods": {
      "lan": "局域网",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "自定义服务器",
      "botFeishu": "飞书机器人",
      "botTelegram": "Telegram Bot",
      "botWeixin": "微信机器人"
    },
    "statuses": {
      "loading": "加载中",
      "running": "运行中",
      "done": "已完成",
      "failed": "失败",
      "cancelled": "已取消"
    }
  },
  "zh-TW": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "遠端控制",
      "codeAgent": "程式碼助手",
      "deepReview": "嚴格審查",
      "settings": "設定",
      "workspace": "工作區",
      "accountLogin": "帳號登入"
    },
    "modes": {
      "agentic": "代理模式",
      "assistant": "助手模式",
      "expert": "專家模式",
      "review": "審查模式"
    },
    "agents": {
      "code": "程式碼會話",
      "cowork": "協作會話",
      "claw": "Claw",
      "default": "預設助手"
    },
    "tools": {
      "explore": "探索",
      "read": "讀取",
      "write": "寫入",
      "shell": "命令列",
      "search": "搜尋",
      "edit": "編輯",
      "todo": "待辦"
    },
    "connectionMethods": {
      "lan": "區域網路",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "自訂伺服器",
      "botFeishu": "飛書機器人",
      "botTelegram": "Telegram Bot",
      "botWeixin": "微信機器人"
    },
    "statuses": {
      "loading": "載入中",
      "running": "執行中",
      "done": "已完成",
      "failed": "失敗",
      "cancelled": "已取消"
    }
  },
  "en-US": {
    "product": {
      "name": "BitFun",
      "remote": "BitFun Remote"
    },
    "features": {
      "remoteControl": "Remote Control",
      "codeAgent": "Code Agent",
      "deepReview": "Review: Strict",
      "settings": "Settings",
      "workspace": "Workspace",
      "accountLogin": "Account Login"
    },
    "modes": {
      "agentic": "Agentic Mode",
      "assistant": "Assistant Mode",
      "expert": "Expert Mode",
      "review": "Review Mode"
    },
    "agents": {
      "code": "Code Session",
      "cowork": "Cowork Session",
      "claw": "Claw",
      "default": "Default Assistant"
    },
    "tools": {
      "explore": "Explore",
      "read": "Read",
      "write": "Write",
      "shell": "Shell",
      "search": "Search",
      "edit": "Edit",
      "todo": "Todo"
    },
    "connectionMethods": {
      "lan": "LAN",
      "ngrok": "Ngrok",
      "bitfunServer": "BitFun Server",
      "customServer": "Custom Server",
      "botFeishu": "Feishu Bot",
      "botTelegram": "Telegram Bot",
      "botWeixin": "WeChat Bot"
    },
    "statuses": {
      "loading": "Loading",
      "running": "Running",
      "done": "Done",
      "failed": "Failed",
      "cancelled": "Cancelled"
    }
  }
} as const satisfies Record<MobileLanguage, SharedI18nTerms>;

export function isMobileLanguage(value: string | null | undefined): value is MobileLanguage {
  return MOBILE_LOCALES.some(locale => locale.id === value);
}

export function resolveMobileLanguage(value: string | null | undefined): MobileLanguage | null {
  const normalized = value?.trim().toLowerCase();
  if (!normalized) return null;

  const exact = MOBILE_LOCALES.find(locale => locale.id.toLowerCase() === normalized);
  if (exact) return exact.id;

  return mobileLocaleAliasesByPriority
    .find(({ alias }) => normalized === alias || normalized.startsWith(`${alias}-`))
    ?.locale.id ?? null;
}

export function getNextMobileLanguage(language: MobileLanguage): MobileLanguage {
  const currentIndex = MOBILE_LOCALES.findIndex(locale => locale.id === language);
  return MOBILE_LOCALES[(currentIndex + 1) % MOBILE_LOCALES.length].id;
}

export function getMobileLanguageShortName(language: MobileLanguage): string {
  return MOBILE_LOCALES.find(locale => locale.id === language)?.shortName ?? language;
}

export function getMobileFallbackChain(language: string | null | undefined, includeSelf = false): MobileLanguage[] {
  const resolved = resolveMobileLanguage(language);
  const locale = resolved ? MOBILE_LOCALES.find(item => item.id === resolved) : null;
  const chain: MobileLanguage[] = locale
    ? [
      ...(includeSelf ? [locale.id] : []),
      ...locale.contentFallbacks,
    ]
    : [...UNKNOWN_LANGUAGE_FALLBACK_CHAIN];

  return Array.from(new Set(chain));
}
