// This file is generated by scripts/generate-i18n-contract.mjs.
// Do not edit it by hand; edit src/shared/i18n/contract/locales.json instead.
export interface InstallerLanguageDefinition {
  uiCode: string;
  appCode: string;
  label: string;
  nativeName: string;
  continueLabel: string;
  aliases: readonly string[];
}

export const INSTALLER_LANGUAGE_DEFINITIONS = [
  {
    uiCode: "en",
    appCode: "en-US",
    label: "English",
    nativeName: "English",
    continueLabel: "Continue",
    aliases: ["en", "en-US"],
  },
  {
    uiCode: "zh",
    appCode: "zh-CN",
    label: "Chinese",
    nativeName: "简体中文",
    continueLabel: "继续",
    aliases: ["zh", "zh-Hans", "zh-CN"],
  },
  {
    uiCode: "zh-TW",
    appCode: "zh-TW",
    label: "Traditional Chinese",
    nativeName: "繁體中文",
    continueLabel: "繼續",
    aliases: ["zh-TW", "zh-Hant", "zh-HK", "zh-MO"],
  }
] as const satisfies readonly InstallerLanguageDefinition[];

export type InstallerUiLanguage = (typeof INSTALLER_LANGUAGE_DEFINITIONS)[number]['uiCode'];
export type AppLanguage = (typeof INSTALLER_LANGUAGE_DEFINITIONS)[number]['appCode'];

export const DEFAULT_INSTALLER_APP_LANGUAGE = "en-US" satisfies AppLanguage;
export const DEFAULT_INSTALLER_UI_LANGUAGE = "en" satisfies InstallerUiLanguage;
